(()=>{
'use strict';
if(document.getElementById('problemReport'))return;
const parent=document.getElementById('dailyTools')||document.querySelector('main')||document.body;
const panel=document.createElement('details');panel.id='problemReport';panel.className='planning';panel.innerHTML='<summary>Signaler un problème</summary><p>Préparez un rapport à transmettre vous-même. Aucune note, progression, identité ou adresse personnelle n’y est ajoutée automatiquement. Ne saisissez pas d’information privée dans votre description. Aucun envoi automatique n’est effectué.</p><label for="problemDescription">Que se passe-t-il ?</label><textarea id="problemDescription" maxlength="2000"></textarea><label><input id="problemIncludeDevice" type="checkbox"> Ajouter le type d’appareil que je choisis</label><label for="problemDevice">Type d’appareil</label><select id="problemDevice"><option value="iphone">iPhone</option><option value="android">Android</option><option value="computer">Ordinateur</option><option value="tablet">Tablette</option></select><button id="downloadProblemReport" type="button">Télécharger le rapport</button><p id="problemReportStatus" role="status"></p>';parent.append(panel);
panel.querySelector('#downloadProblemReport').onclick=()=>{const description=panel.querySelector('#problemDescription').value.trim();if(!description){panel.querySelector('#problemReportStatus').textContent='Décrivez le problème avant de préparer le rapport.';return}const file=location.pathname.split('/').pop()||'index.html',data={applicationVersion:window.bibleAppRelease,page:file,day:typeof current==='number'?current:null,description};if(panel.querySelector('#problemIncludeDevice').checked)data.deviceType=panel.querySelector('#problemDevice').value;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='probleme-application-biblique.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);panel.querySelector('#problemReportStatus').textContent='Rapport préparé. Vérifiez son contenu avant de le transmettre.'};
const history=document.createElement('p'),link=document.createElement('a');link.href='./nouveautes.html';link.textContent='Nouveautés et historique · version '+window.bibleAppRelease;history.append(link);(document.querySelector('.app-update')||parent).append(history);
if(document.getElementById('backupCheckFile')){const button=document.createElement('button');button.id='verifyDownloadedBackup';button.type='button';button.textContent='Vérifier le fichier que je viens de télécharger';button.hidden=true;document.getElementById('secureBackupPanel')?.append(button);button.onclick=()=>{const panel=document.getElementById('backupCheckPanel');for(let p=panel;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;document.getElementById('chooseBackupCheck').click()};window.addEventListener('bible-backup-exported',()=>{button.hidden=false;const status=document.getElementById('secureBackupStatus');status.textContent+=' Vous pouvez rouvrir le fichier téléchargé pour vérifier son mot de passe et son contenu, sans l’importer.'})}
})();
