(()=>{
'use strict';
const home=!!document.getElementById('personalHome'),isHome=location.pathname.endsWith('/index.html')||location.pathname.endsWith('/');
const names=['classique','genres','salut','semaines','chronologique','parallele','rattrapage','famille','continuite','israel-nations','connexions','reseau'];
const get=k=>{try{return localStorage.getItem(k)}catch(_){return null}},set=(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}};
function scope(){if(isHome){const plan=get('bible-app-selected-plan-v1'),v=document.getElementById('homeVersion')?.value||get('bible-app-version-v1')||'s21';return names.includes(plan)&&['s21','lsg','pdv'].includes(v)?{plan,v}:null}const m=location.pathname.match(/plan-([a-z-]+?)(?:-(lsg|pdv))?\.html$/);return m&&names.includes(m[1])?{plan:m[1],v:m[2]||'s21'}:null}
function prefix(s){return s.plan==='classique'&&s.v==='s21'?'bible-plan':'bible-'+s.plan+(s.v==='s21'?'':'-'+s.v)+'-v1'}
function key(s){return 'bible-backup-reminder-'+s.plan+'-'+s.v+'-v1'}
function hasProgress(s){try{if(['connexions','reseau'].includes(s.plan)){const d=JSON.parse(get('bible-'+s.plan+'-'+s.v+'-v1-state')||'{}');return !!(d.completedDays?.length||Object.values(d.notes||{}).some(Boolean))}const p=prefix(s);return !!(JSON.parse(get(p+'-completed')||'[]').length||Object.values(JSON.parse(get(p+'-notes')||'{}')).some(Boolean))}catch(_){return false}}
function read(s){try{return JSON.parse(get(key(s))||'{}')}catch(_){return {}}}
let panel=null;
function render(){const s=scope();if(!s||(!isHome&&!['connexions','reseau'].includes(s.plan)))return;if(!panel){panel=document.createElement('section');panel.id='backupSummary';panel.className='backup-summary';panel.setAttribute('aria-label','Ma sauvegarde');if(isHome)(document.getElementById('dailyVerse')||document.getElementById('personalHome')).after(panel);else document.getElementById('transferStatus').after(panel)}const record=read(s),stamp=record.at||get(prefix(s)+'-last-export-at'),date=Date.parse(stamp||''),now=Date.now(),due=hasProgress(s)&&(!Number.isFinite(date)||now-date>=7*86400000)&&now>Number(record.snooze||0);panel.replaceChildren();const title=document.createElement('h2');title.textContent='Ma sauvegarde';const info=document.createElement('p');info.id='backupExportDate';info.textContent=Number.isFinite(date)?'Dernier export lancé sur cet appareil : '+new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(date))+'.':'Aucun export enregistré pour ce parcours et cette version sur cet appareil.';const hint=document.createElement('p');hint.className='status';hint.textContent='Cette date indique qu’un téléchargement a été lancé. Gardez le fichier dans un endroit sûr ; l’application ne peut pas vérifier où vous l’avez conservé.';panel.append(title,info,hint);if(isHome){const a=document.createElement('a');a.href='./plan-'+s.plan+(s.v==='s21'?'':'-'+s.v)+'.html?sauvegarder=1';a.textContent='Sauvegarder ce parcours';panel.append(a)}if(due){const reminder=document.createElement('p');reminder.id='backupGentleReminder';reminder.textContent='Pensez à sauvegarder votre suivi pour pouvoir le retrouver sur un autre appareil.';const button=document.createElement('button');button.type='button';button.textContent='Me le rappeler dans une semaine';button.onclick=()=>{set(key(s),JSON.stringify({...read(s),snooze:Date.now()+7*86400000}));render()};panel.append(reminder,button)}}
window.addEventListener('bible-backup-exported',()=>{const s=scope();if(!s)return;set(key(s),JSON.stringify({at:new Date().toISOString(),snooze:0}));setTimeout(render,0)});
document.getElementById('homeVersion')?.addEventListener('change',render);window.addEventListener('storage',render);window.addEventListener('pageshow',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});let timer;document.addEventListener('input',e=>{if(e.target.id==='sessionNotes'){clearTimeout(timer);timer=setTimeout(render,600)}});document.addEventListener('change',e=>{if(e.target.id==='sessionCompleted')setTimeout(render,0)});
render();
if(!isHome&&new URLSearchParams(location.search).get('sauvegarder')==='1'){const target=document.getElementById('exportConnections')||document.getElementById('exportProtectedBackup')||document.getElementById('exportBackup');if(target){for(let e=target.parentElement;e;e=e.parentElement)if(e.tagName==='DETAILS')e.open=true;const guide=document.getElementById('startGuide');if(guide?.open)document.getElementById('dismissStartGuide')?.click();target.scrollIntoView({block:'center'});target.focus()}}
})();
