(()=>{'use strict';
const db=JSON.parse(document.getElementById('connectionsData').textContent),v=document.body.dataset.version,items=db.sessions,N=items.length,prefix='bible-connexions-'+v+'-v1',player=document.getElementById('player'),$=id=>document.getElementById(id);let current=1,audioIndex=-1,noteTimer;
const validDay=n=>Number.isInteger(n)&&n>=1&&n<=N;
function validNotes(x){return x&&typeof x==='object'&&!Array.isArray(x)&&Object.entries(x).every(([k,t])=>/^[1-9]\d*$/.test(k)&&validDay(Number(k))&&typeof t==='string'&&t.length<=8000)}
let state={completedDays:[],notes:{},lastDay:1};try{const d=JSON.parse(localStorage.getItem(prefix+'-state')||'null');if(d&&Array.isArray(d.completedDays)&&d.completedDays.every(validDay)&&validNotes(d.notes)&&validDay(d.lastDay))state=d}catch(_){}
function store(next){try{localStorage.setItem(prefix+'-state',JSON.stringify(next));state=next;return true}catch(_){$('saveStatus').textContent='Le suivi n’a pas pu être enregistré. Exportez une sauvegarde avant de fermer.';return false}}
function saveNote(){clearTimeout(noteTimer);return store({...state,notes:{...state.notes,[current]:$('sessionNotes').value},lastDay:current})}
function node(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
function link(text,url){const a=node('a',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a}
function refs(){return items[current-1].chapters}
function progress(){$('progress').textContent=state.completedDays.length+' / '+N+' séances validées — rythme libre';$('sessionCompleted').checked=state.completedDays.includes(current)}
function audioState(){const entries=refs();$('audioPosition').textContent=audioIndex<0?'Aucun chapitre sélectionné':(audioIndex+1)+' sur '+entries.length+' — '+entries[audioIndex].title;$('audioPrevious').disabled=audioIndex<=0;$('audioNext').disabled=audioIndex<0||audioIndex>=entries.length-1}
function chooseAudio(i,play=true){if(i<0||i>=refs().length)return;const e=refs()[i];if(!e.src){$('audioStatus').textContent='Audio direct indisponible. Utilisez le lien externe du chapitre.';return}audioIndex=i;player.src=e.src;audioState();$('audioStatus').textContent='';if('mediaSession'in navigator&&typeof MediaMetadata!=='undefined'){navigator.mediaSession.metadata=new MediaMetadata({title:e.title,artist:'Connexions bibliques',album:db.versionLabel})}if(play)player.play().catch(()=>{$('audioStatus').textContent='Appuyez sur lecture pour démarrer, ou utilisez le lien audio externe.'})}
function render(n){if(!validDay(n))return;current=n;audioIndex=-1;player.pause();player.removeAttribute('src');player.load();const s=items[n-1],box=$('sessionContent');box.replaceChildren();box.append(node('h2','Séance '+n+' — '+s.title),node('p',s.direction+' · '+s.kind));const readings=node('div','');readings.className='connection-readings';s.chapters.forEach((e,i)=>{const c=node('article','');c.append(node('h3',e.title),node('p',i===0?'Chapitre de départ':i===1?'Chapitre associé':'Complément facultatif'));const row=node('div','');row.className='connection-actions';row.append(link('Lire le chapitre',e.textPage||e.page),link('Audio externe',e.audioPage||e.page));const b=node('button','Écouter ici');b.type='button';b.disabled=!e.src;b.onclick=()=>chooseAudio(i);row.append(b);c.append(row);readings.append(c)});box.append(readings);for(const [heading,key]of [['Versets qui fondent le lien','anchorLabel'],['Le contexte','context'],['Comprendre le rapprochement','reading'],['Ce que le lien ne permet pas d’affirmer','limit']]){box.append(node('h3',heading),node('p',s[key]))}const sources=node('p','Vérifier dans les textes : ');for(const a of s.anchorLinks){sources.append(link(a.label,a.url),document.createTextNode(' ; '))}box.append(sources);const details=node('details','');details.open=true;details.append(node('summary','Questions pour approfondir'));const list=node('ol','');s.questions.forEach(q=>list.append(node('li',q)));details.append(list);box.append(details);$('sessionSelect').value=String(n);$('sessionNotes').value=state.notes[n]||'';$('previousSession').disabled=n===1;$('nextSession').disabled=n===N;progress();audioState();history.replaceState(null,'','#seance-'+n);store({...state,lastDay:n});$('sessionAnnouncement').textContent='Séance '+n+' sur '+N+' : '+s.title}
items.forEach((s,i)=>$('sessionSelect').add(new Option((i+1)+' — '+s.title,i+1)));$('sessionSelect').onchange=()=>{if(saveNote())render(Number($('sessionSelect').value))};$('previousSession').onclick=()=>{if(saveNote())render(current-1)};$('nextSession').onclick=()=>{if(saveNote())render(current+1)};$('resumeSession').onclick=()=>{if(saveNote())render(items.findIndex((s,i)=>!state.completedDays.includes(i+1))+1||current)};
$('sessionNotes').oninput=()=>{clearTimeout(noteTimer);$('saveStatus').textContent='Enregistrement en cours…';noteTimer=setTimeout(()=>{if(saveNote())$('saveStatus').textContent='Note enregistrée sur cet appareil.'},350)};$('saveNote').onclick=()=>{if(saveNote())$('saveStatus').textContent='Note enregistrée sur cet appareil.'};$('sessionCompleted').onchange=()=>{const done=$('sessionCompleted').checked;store({...state,completedDays:done?[...new Set([...state.completedDays,current])]:state.completedDays.filter(n=>n!==current)});progress()};
$('audioPrevious').onclick=()=>chooseAudio(audioIndex-1);$('audioNext').onclick=()=>chooseAudio(audioIndex+1);player.onended=()=>{if($('audioChain').checked&&audioIndex<refs().length-1)chooseAudio(audioIndex+1)};player.onerror=()=>{$('audioStatus').textContent='Audio inaccessible pour le moment. Essayez le lien audio externe.'};
let speed='1';try{speed=localStorage.getItem(prefix+'-speed')||'1'}catch(_){}if(!['0.75','1','1.25','1.5','2'].includes(speed))speed='1';$('audioSpeed').value=speed;player.playbackRate=Number(speed);$('audioSpeed').onchange=()=>{player.playbackRate=Number($('audioSpeed').value);try{localStorage.setItem(prefix+'-speed',$('audioSpeed').value)}catch(_){}};player.onloadedmetadata=()=>{player.playbackRate=Number($('audioSpeed').value)};
if('mediaSession'in navigator){for(const [name,fn]of [['play',()=>player.play().catch(()=>{})],['pause',()=>player.pause()],['previoustrack',()=>chooseAudio(audioIndex-1)],['nexttrack',()=>chooseAudio(audioIndex+1)]])try{navigator.mediaSession.setActionHandler(name,fn)}catch(_){}}
$('connectionVersion').value=v;$('connectionVersion').onchange=()=>{if(!saveNote())return;location.href='./plan-connexions'+($('connectionVersion').value==='s21'?'':'-'+$('connectionVersion').value)+'.html#seance-'+current};
function snapshot(){return {format:'bible-connexions-suivi',edition:'connexions-24-v1',version:1,bibleVersion:v,...state}}
function validate(d){if(!d||d.format!=='bible-connexions-suivi'||d.edition!=='connexions-24-v1'||d.version!==1||d.bibleVersion!==v||!Array.isArray(d.completedDays)||d.completedDays.length>N||!d.completedDays.every(validDay)||new Set(d.completedDays).size!==d.completedDays.length||!validNotes(d.notes)||!validDay(d.lastDay))throw Error('Fichier incompatible avec ce parcours ou cette version de Bible.');return d}
const enc=new TextEncoder(),dec=new TextDecoder(),aad=enc.encode('BibleConnections-v1');function b64(x){let s='';for(let i=0;i<x.length;i+=8192)s+=String.fromCharCode(...x.subarray(i,i+8192));return btoa(s)}function bytes(x){if(typeof x!=='string'||x.length>2000000||!/^[A-Za-z0-9+/]*={0,2}$/.test(x))throw Error('Fichier protégé invalide.');return Uint8Array.from(atob(x),c=>c.charCodeAt(0))}
async function key(pw,salt){if(!crypto.subtle)throw Error('Protection indisponible ici : utilisez une page HTTPS.');const m=await crypto.subtle.importKey('raw',enc.encode(pw.normalize('NFC')),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function protect(d,pw){if(pw.length<12||pw.length>1024)throw Error('Utilisez une phrase secrète de 12 à 1 024 caractères.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},await key(pw,salt),enc.encode(JSON.stringify(d))));return {format:'bible-connexions-protege',version:1,iterations:600000,salt:b64(salt),iv:b64(iv),cipher:b64(cipher)}}
async function unprotect(d,pw){if(d.version!==1||d.iterations!==600000)throw Error('Protection non reconnue.');const salt=bytes(d.salt),iv=bytes(d.iv),cipher=bytes(d.cipher);if(salt.length!==16||iv.length!==12||cipher.length>1000000||pw.length<12||pw.length>1024)throw Error('Fichier ou phrase secrète invalide.');try{return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:aad},await key(pw,salt),cipher)))}catch(_){throw Error('Phrase secrète incorrecte ou fichier altéré.')}}
function download(d){const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})),a=node('a','');a.href=url;a.download='connexions-'+v+'-suivi.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('exportConnections').onclick=async()=>{try{if(!saveNote())return;const pw=$('connectionsPassword').value;if(pw&&pw!==$('connectionsPasswordConfirm').value)throw Error('Les phrases secrètes ne correspondent pas.');const d=pw?await protect(snapshot(),pw):snapshot();download(d);$('transferStatus').textContent=pw?'Sauvegarde protégée préparée. Gardez sa phrase secrète.':'Sauvegarde préparée sans protection : elle contient vos notes personnelles.'}catch(e){$('transferStatus').textContent=e.message}finally{$('connectionsPassword').value='';$('connectionsPasswordConfirm').value=''}};
let pending=null;$('importConnections').onchange=async()=>{pending=null;$('importPreview').hidden=true;try{const f=$('importConnections').files[0];if(!f)return;if(f.size>2000000)throw Error('Fichier trop volumineux.');let d=JSON.parse(await f.text());if(d.format==='bible-connexions-protege')d=await unprotect(d,$('connectionsPassword').value);pending=validate(d);$('importPreviewText').textContent=d.completedDays.length+' séances validées ; '+Object.values(d.notes).filter(Boolean).length+' notes. Votre suivi de cette version sera remplacé seulement après confirmation. Exportez-le auparavant si vous souhaitez le conserver.';$('importPreview').hidden=false;$('transferStatus').textContent='Fichier vérifié. Aucun changement pour le moment.'}catch(e){$('transferStatus').textContent=e.message||'Fichier invalide.'}finally{$('connectionsPassword').value='';$('connectionsPasswordConfirm').value='';$('importConnections').value=''}};
$('confirmConnectionsImport').onclick=()=>{if(!pending)return;const d=pending;if(store({completedDays:[...d.completedDays],notes:{...d.notes},lastDay:d.lastDay})){pending=null;$('importPreview').hidden=true;render(d.lastDay);$('transferStatus').textContent='Suivi importé dans cette version uniquement.'}};$('cancelConnectionsImport').onclick=()=>{pending=null;$('importPreview').hidden=true;$('transferStatus').textContent='Import annulé. Suivi conservé.'};
document.addEventListener('visibilitychange',()=>{if(document.hidden)saveNote()});window.addEventListener('pagehide',saveNote);
try{localStorage.setItem('bible-app-selected-plan-v1','connexions');localStorage.setItem('bible-app-version-v1',v)}catch(_){}const hash=Number(location.hash.match(/^#(?:seance|jour)-(\d+)$/)?.[1]);render(validDay(hash)?hash:state.lastDay);
})();
