(()=>{
'use strict';
const content=document.getElementById('content');if(!content)return;
const file=location.pathname.split('/').pop(),plan=file.replace(/^plan-/,'').replace(/(?:-lsg|-pdv)?\.html$/,'');
function add(){const section=content.querySelector('.day');if(!section||section.querySelector('.editorial-context'))return;
const box=document.createElement('details');box.className='editorial-context';const summary=document.createElement('summary');summary.textContent='Lire ces passages dans leur contexte';box.append(summary);
const p=document.createElement('p');p.textContent='Repérez qui parle, à qui, et dans quelle situation. Pour un extrait, lisez aussi ce qui le précède et le suit. Un rapprochement proposé sert à l’étude : vérifiez-le dans les textes, en respectant leurs différences.';box.append(p);
if(plan==='classique'){const heading=section.querySelector('.theology .kind');if(heading&&!heading.dataset.editorial){heading.textContent='Piste d’étude — '+heading.textContent;heading.dataset.editorial='true'}}
const links=document.createElement('div');links.className='editorial-context-links';const seen=new Set();const d=days[current-1];
for(const c of d.cards)for(const e of c.entries){const page=e.textPage||e.page?.replace('/audio-bible/','/bible/');if(!page||seen.has(e.title))continue;seen.add(e.title);const link=document.createElement('a');link.textContent='Contexte : '+e.title;const whole=new URL(page);if(whole.hostname==='www.biblegateway.com'){const search=whole.searchParams.get('search');if(search)whole.searchParams.set('search',search.replace(/:\d+(?:[-–]\d+)?$/,''))}else whole.pathname=whole.pathname.replace(/(\.[0-9]+)\.[0-9]+(?:-[0-9]+)?(?=\.[A-Z0-9]+$)/,'$1');link.href=whole.href;link.target='_blank';link.rel='noopener noreferrer';links.append(link)}box.append(links);
if(plan==='chronologique'){const p=document.createElement('p');p.textContent='L’ordre de ce parcours est pédagogique et indicatif. Il ne fixe pas avec certitude la date de rédaction des livres. Les récits parallèles présentent des points de vue distincts.';box.append(p);const books=d.cards.flatMap(c=>c.entries).map(e=>e.book||e.page?.match(/\/([A-Z0-9]+)\./)?.[1]);if(books.some(b=>['JOB','PSA','JOL'].includes(b))){const caution=document.createElement('p');caution.textContent='Repère discuté : le placement de Job, de nombreux Psaumes et de Joël reste incertain. Le thème ou la période retenue ici ne constitue pas une datation établie.';box.append(caution)}}
if(plan==='famille'){const p=document.createElement('p');p.textContent='Pour un jeune enfant, retenez une question d’observation et une explication simple. Avec des lecteurs plus avancés, comparez les réponses au texte et à son contexte. Si une question ne correspond pas à l’extrait, reformulez-la ou passez-la : ne forcez pas le texte à répondre au thème. Chacun peut passer une question ou ne pas partager une expérience personnelle. Les thèmes difficiles peuvent être abordés séparément avec un adulte.';box.append(p)}
const more=document.createElement('a');more.href='./qualite-des-plans.html';more.textContent='Méthode et limites des huit parcours';box.append(more);section.append(box)}
new MutationObserver(add).observe(content,{childList:true});add();
})();
