(()=>{
const audio=document.getElementById('player');if(!audio)return;
const dock=document.createElement('nav');dock.id='mobileDock';dock.setAttribute('aria-label','Navigation mobile');
const plans=document.createElement('a');plans.href='./index.html?choisir=1';plans.textContent='Plans';const search=document.createElement('a');search.href='./recherche.html';search.textContent='Recherche';
function control(id,label,target){const b=document.createElement('button');b.type='button';b.id=id;b.textContent=label;b.onclick=()=>{const t=document.getElementById(target);if(t&&!t.disabled)t.click()};return b}
const prev=control('mobilePrevious','← Jour','previous'),next=control('mobileNext','Jour →','next'),listen=document.createElement('button');listen.type='button';listen.textContent='Audio';listen.onclick=()=>{const section=audio.closest('.player');if(section)section.scrollIntoView({block:'start',behavior:'smooth'})};dock.append(plans,prev,next,listen,search);document.body.append(dock);
function sync(){prev.disabled=document.getElementById('previous').disabled;next.disabled=document.getElementById('next').disabled}
new MutationObserver(sync).observe(document.getElementById('previous'),{attributes:true,attributeFilter:['disabled']});new MutationObserver(sync).observe(document.getElementById('next'),{attributes:true,attributeFilter:['disabled']});sync();
const help=document.createElement('details');help.className='background-audio-help';const summary=document.createElement('summary');summary.textContent='Écouter avec l’écran verrouillé';const text=document.createElement('p');text.textContent='Démarrez un chapitre avant de verrouiller l’écran. Les commandes du téléphone peuvent afficher le titre, lecture/pause et le chapitre précédent ou suivant selon le navigateur. Activez « Enchaîner les chapitres » pour continuer les lectures du jour. Gardez cette page ouverte : quitter le plan ou fermer le navigateur interrompt l’écoute. Si le téléphone suspend la lecture, revenez au lecteur ou utilisez « Reprendre ». Le minuteur peut être retardé lorsque le système suspend la page.';help.append(summary,text);audio.closest('.player').append(help);
try{if('audioSession' in navigator)navigator.audioSession.type='playback'}catch(_){}
if(!('mediaSession' in navigator))return;
const session=navigator.mediaSession;
function action(name,fn){try{session.setActionHandler(name,fn)}catch(_){}}
function skip(id){const b=document.getElementById(id);if(b&&!b.disabled)b.click()}
function seek(offset){if(!Number.isFinite(audio.duration))return;audio.currentTime=Math.max(0,Math.min(audio.duration,audio.currentTime+offset));position()}
function position(){if(!session.setPositionState)return;try{if(Number.isFinite(audio.duration)&&audio.duration>0&&Number.isFinite(audio.currentTime))session.setPositionState({duration:audio.duration,playbackRate:audio.playbackRate,position:Math.min(audio.duration,Math.max(0,audio.currentTime))});else session.setPositionState()}catch(_){}}
function metadata(){if(!audio.hasAttribute('src')){session.metadata=null;session.playbackState='none';return}const title=document.getElementById('playing').textContent;const version=document.getElementById('bibleVersion')?.value==='lsg'?'Segond — Trésor Sonore':document.getElementById('bibleVersion')?.value==='pdv'?'Parole de Vie 2017':'Segond 21';try{session.metadata=new MediaMetadata({title,artist:version,album:'Bible en un an',artwork:[{src:new URL('./icon-512.png',location.href).href,sizes:'512x512',type:'image/png'}]})}catch(_){}action('previoustrack',document.getElementById('audioPrevious').disabled?null:()=>skip('audioPrevious'));action('nexttrack',document.getElementById('audioNext').disabled?null:()=>skip('audioNext'));position()}
action('play',()=>{if(audio.hasAttribute('src'))audio.play().catch(()=>{document.getElementById('status').textContent='Touchez le lecteur pour reprendre l’écoute.'})});action('pause',()=>audio.pause());action('stop',()=>audio.pause());action('seekbackward',d=>seek(-(d.seekOffset||15)));action('seekforward',d=>seek(d.seekOffset||15));action('seekto',d=>{if(Number.isFinite(d.seekTime)&&Number.isFinite(audio.duration)){audio.currentTime=Math.max(0,Math.min(d.seekTime,audio.duration));position()}});
audio.addEventListener('playing',()=>{session.playbackState='playing';metadata()});audio.addEventListener('pause',()=>{session.playbackState=audio.hasAttribute('src')?'paused':'none';position()});
for(const name of ['loadedmetadata','durationchange','seeked','ratechange','timeupdate'])audio.addEventListener(name,position);
new MutationObserver(metadata).observe(audio,{attributes:true,attributeFilter:['src']});new MutationObserver(metadata).observe(document.getElementById('playing'),{childList:true,subtree:true,characterData:true});
})();