(()=>{
'use strict';
const content=document.getElementById('content');if(!content)return;
const categories=['Question ouverte','À approfondir','Important'],norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e};
const panel=el('details');panel.id='personalNotebook';panel.className='planning';panel.innerHTML='<summary>Mon carnet de relecture</summary><p>Retrouvez vos notes, questions ouvertes, passages à approfondir et journées importantes dans ce parcours et cette version. La recherche reste sur cet appareil. Les catégories sont vos thèmes personnels et figurent dans les sauvegardes habituelles.</p><label for="notebookQuery">Rechercher dans mon carnet</label><input id="notebookQuery" type="search" maxlength="150" placeholder="Mot, thème personnel ou référence"><label for="notebookFilter">Afficher</label><select id="notebookFilter"><option value="all">Tout mon carnet</option><option value="questions">Questions ouvertes</option><option value="deeper">À approfondir</option><option value="important">Notes importantes</option><option value="favorites">Journées favorites</option></select><p id="notebookStatus" role="status"></p><div id="notebookResults"></div><button id="notebookMore" type="button" hidden>Afficher les 20 suivantes</button><button id="notebookSave" type="button">Sauvegarder mon suivi et mon carnet</button>';
(document.getElementById('dailyTools')||document.querySelector('main')).append(panel);
const opener=el('button','Mon carnet');opener.type='button';opener.id='openPersonalNotebook';opener.setAttribute('aria-controls',panel.id);(document.querySelector('.daily-ui-actions')||document.querySelector('main')).append(opener);opener.onclick=()=>{const ancestor=panel.closest('#dailyTools');if(ancestor)ancestor.open=true;panel.open=true;search();panel.scrollIntoView({block:'start'});panel.querySelector('#notebookQuery').focus({preventScroll:true})};
const query=panel.querySelector('#notebookQuery'),filter=panel.querySelector('#notebookFilter'),results=panel.querySelector('#notebookResults'),status=panel.querySelector('#notebookStatus'),more=panel.querySelector('#notebookMore');let matches=[],shown=0,timer;
function tagged(n,tag){return (noteTopics[n]||[]).some(t=>norm(t)===norm(tag))}
function search(){const words=norm(query.value).split(/\s+/).filter(Boolean),category={questions:categories[0],deeper:categories[1],important:categories[2]}[filter.value];matches=[];for(let i=1;i<=days.length;i++){const text=notes[i]||'',tags=noteTopics[i]||[],favorite=favoriteDays.has(i);if(!text.trim()&&!tags.length&&!favorite)continue;if(category&&!tagged(i,category)||filter.value==='favorites'&&!favorite)continue;const refs=days[i-1].cards.map(c=>c.ref).join(' ; '),haystack=norm(text+' '+tags.join(' ')+' '+refs+' '+days[i-1].theme+' jour '+i);if(words.every(w=>haystack.includes(w)))matches.push({day:i,text,tags,refs,favorite})}results.replaceChildren();shown=0;status.textContent=matches.length?matches.length+' journée(s) dans votre carnet.':'Aucune journée trouvée. Notez une question ou classez une journée depuis vos notes.';append()}
function append(){const frag=document.createDocumentFragment();for(const r of matches.slice(shown,shown+20)){const article=el('article');article.className='notebook-entry';article.append(el('h3','Jour '+r.day+' — '+days[r.day-1].theme),el('p',r.refs),el('p',r.tags.join(' · ')+(r.favorite?' · Journée favorite':'')));if(r.text){article.append(el('p',r.text.length>600?r.text.slice(0,600)+'…':r.text));if(r.text.length>600){const full=el('details');full.append(el('summary','Lire la note entière'),el('p',r.text));article.append(full)}}else article.append(el('p','Journée classée sans note écrite.'));const open=el('button','Retrouver les lectures et ma note');open.type='button';open.onclick=()=>{render(r.day);requestAnimationFrame(()=>{const note=document.getElementById('dailyNotes');note.scrollIntoView({block:'center'});note.focus({preventScroll:true})})};article.append(open);frag.append(article)}shown=Math.min(matches.length,shown+20);results.append(frag);more.hidden=shown>=matches.length}
query.oninput=()=>{clearTimeout(timer);timer=setTimeout(search,150)};filter.onchange=search;more.onclick=append;panel.ontoggle=()=>{if(panel.open)search()};panel.querySelector('#notebookSave').onclick=()=>window.secureBackup?.startExport();
function addControls(){const notesPanel=document.getElementById('dailyNotesPanel');if(!notesPanel||notesPanel.querySelector('.notebook-classification'))return;const group=el('div');group.className='notebook-classification';group.setAttribute('role','group');group.setAttribute('aria-label','Classer cette journée dans mon carnet');group.append(el('p','Classer cette journée dans mon carnet'));const feedback=el('p');feedback.setAttribute('role','status');for(const label of categories){const button=el('button',label);button.type='button';button.dataset.notebookCategory=label;button.setAttribute('aria-pressed',String(tagged(current,label)));button.onclick=()=>{const old=[...(noteTopics[current]||[])],present=tagged(current,label),tags=present?old.filter(t=>norm(t)!==norm(label)):[...old,label];if(tags.length>8){feedback.textContent='Huit thèmes personnels au maximum. Retirez un thème avant d’ajouter cette catégorie.';return}const updated={...noteTopics};if(tags.length)updated[current]=tags;else delete updated[current];try{localStorage.setItem(topicsKey,JSON.stringify(updated))}catch(_){feedback.textContent='Classification non enregistrée : le stockage de cet appareil est indisponible.';return}noteTopics=updated;document.getElementById('dailyNoteTopics').value=tags.join(', ');group.querySelectorAll('[data-notebook-category]').forEach(b=>b.setAttribute('aria-pressed',String(tagged(current,b.dataset.notebookCategory))));refreshPersonalThemes();refreshBackupReminder();feedback.textContent=present?'Catégorie retirée ; votre note reste conservée.':'Journée classée : '+label+'.';if(panel.open)search()};group.append(button)}group.append(feedback);notesPanel.append(group);if(panel.open)search()}
content.addEventListener('input',()=>{if(panel.open){clearTimeout(timer);timer=setTimeout(search,150)}});content.addEventListener('click',e=>{if(panel.open&&e.target.closest('#favoriteDay'))requestAnimationFrame(search)});content.addEventListener('change',()=>{document.querySelectorAll('[data-notebook-category]').forEach(b=>b.setAttribute('aria-pressed',String(tagged(current,b.dataset.notebookCategory))));if(panel.open)search()});new MutationObserver(addControls).observe(content,{childList:true});addControls();
})();
