(()=>{
'use strict';
const plans={classique:'Thèmes et rapprochements',genres:'Lecture par genres',salut:'Histoire du salut',semaines:'Semaines thématiques',chronologique:'Lecture chronologique',parallele:'Ancien et Nouveau Testament',rattrapage:'Lecture avec pauses',famille:'Lecture en famille'},versions={s21:'Segond 21',lsg:'Segond — Trésor Sonore',pdv:'Parole de Vie'};
const panel=document.createElement('details');panel.id='offlineTools';panel.className='planning';panel.innerHTML='<summary>Mes parcours hors connexion</summary><p>Seuls les parcours que vous ouvrez ou téléchargez sont conservés sur cet appareil. Les fichiers audio et les textes bibliques externes nécessitent Internet.</p><label for="offlinePlan">Plan</label><select id="offlinePlan"></select><label for="offlineVersion">Version</label><select id="offlineVersion"></select><button id="prepareOffline" type="button">Télécharger ce parcours</button><p id="offlineResult" role="status" aria-live="polite"></p><ul id="offlineList"></ul>';
(document.getElementById('dailyTools')||document.querySelector('main')||document.body).append(panel);
for(const [v,t]of Object.entries(plans))panel.querySelector('#offlinePlan').add(new Option(t,v));
for(const [v,t]of Object.entries(versions))panel.querySelector('#offlineVersion').add(new Option(t,v));
const status=panel.querySelector('#offlineResult'),btn=panel.querySelector('#prepareOffline');
function filename(){return 'plan-'+panel.querySelector('#offlinePlan').value+(panel.querySelector('#offlineVersion').value==='s21'?'':'-'+panel.querySelector('#offlineVersion').value)+'.html'}
async function request(type,extra={}){const registration=await navigator.serviceWorker.ready,worker=registration.active;if(!worker)throw Error('worker');return new Promise((resolve,reject)=>{const ch=new MessageChannel(),timer=setTimeout(()=>reject(Error('timeout')),45000);ch.port1.onmessage=e=>{clearTimeout(timer);ch.port1.close();e.data.ok?resolve(e.data):reject(Error('download'))};worker.postMessage({type,...extra},[ch.port2])})}
async function refresh(){const {files}=await request('LIST_OFFLINE');const list=panel.querySelector('#offlineList');list.replaceChildren();for(const file of files){const m=file.match(/^plan-(.+?)(?:-(lsg|pdv))?\.html$/),li=document.createElement('li'),remove=document.createElement('button');li.append((plans[m[1]]||m[1])+' — '+versions[m[2]||'s21']+' ');remove.textContent='Retirer le téléchargement';remove.onclick=async()=>{try{await request('REMOVE_PLAN',{file});await refresh();status.textContent='Téléchargement retiré. Vos coches et notes sont conservées.'}catch(_){status.textContent='Impossible de retirer ce téléchargement.'}};li.append(remove);list.append(li)}if(!files.length)list.append(document.createTextNode('Aucun parcours téléchargé.'));const old=document.getElementById('offlineStatus');if(old)old.textContent=files.includes(location.pathname.split('/').pop())?'Ce parcours est disponible hors connexion. L’audio et les textes externes nécessitent Internet.':'Téléchargez le parcours pour le rendre disponible hors connexion.';return files}
async function prepare(file){btn.disabled=true;status.textContent='Téléchargement du parcours…';try{await request('PREPARE_PLANS',{files:[file]});await refresh();status.textContent='Parcours disponible hors connexion sur cet appareil.'}catch(_){status.textContent='Téléchargement non terminé. Retrouvez une connexion puis réessayez.'}finally{btn.disabled=false}}
if(!('serviceWorker'in navigator)||!['https:','http:'].includes(location.protocol)){btn.disabled=true;status.textContent='Publiez l’application sur GitHub Pages pour activer les téléchargements hors connexion.';return}
btn.onclick=()=>prepare(filename());
const currentFile=location.pathname.split('/').pop(),match=currentFile.match(/^plan-(.+?)(?:-(lsg|pdv))?\.html$/);if(match){panel.querySelector('#offlinePlan').value=match[1];panel.querySelector('#offlineVersion').value=match[2]||'s21'}
window.bibleAppWorkerReady().then(async()=>{const files=await refresh();if(match){if(files.includes(currentFile))status.textContent='Parcours disponible hors connexion sur cet appareil.';else await prepare(currentFile)}}).catch(()=>{status.textContent='Accès hors connexion indisponible.'});
})();
