(()=>{
'use strict';
const selected=(()=>{try{return localStorage.getItem('bible-app-selected-plan-v1')}catch(_){return null}})(),names={classique:'Plan avec thèmes',genres:'Lecture par genres',salut:'Histoire du salut',semaines:'Semaines thématiques',chronologique:'Lecture chronologique',parallele:'Ancien et Nouveau Testament en parallèle',rattrapage:'Lecture avec rattrapage',famille:'En famille ou petit groupe',continuite:'Lecture avec continuité','israel-nations':"Israël et les nations : un seul peuple en Christ"};
if(!names[selected])return;
const main=document.querySelector('main'),section=document.createElement('section');section.id='personalHome';section.setAttribute('aria-label','Mon parcours');main.querySelector('h1').after(section);
function refresh(){let v='s21',completed=[],last=1,companion=null,marks={};try{v=document.getElementById('homeVersion').value;const prefix=v==='s21'?({classique:'bible-plan',genres:'bible-genres-v1',salut:'bible-salut-v1',semaines:'bible-semaines-v1'}[selected]||'bible-'+selected+'-s21-v1'):'bible-'+selected+'-'+v+'-v1';const raw=JSON.parse(localStorage.getItem(prefix+'-completed-days-v1')||'[]');if(Array.isArray(raw))completed=raw.filter(n=>Number.isInteger(n)&&n>=1&&n<=365);const n=Number(localStorage.getItem(prefix+'-last-day'));if(Number.isInteger(n)&&n>=1&&n<=365)last=n;marks=JSON.parse(localStorage.getItem(prefix+'-reading-marks-v1')||'{}');const file='plan-'+selected+(v==='s21'?'':'-'+v)+'.html';companion=JSON.parse(localStorage.getItem('bible-daily-companion-v1-'+file)||'null')}catch(_){}
const url='./plan-'+selected+(v==='s21'?'':'-'+v)+'.html',next=Array.from({length:365},(_,i)=>i+1).find(n=>!completed.includes(n));section.replaceChildren();const title=document.createElement('h2');title.textContent='Mon parcours : '+names[selected];const status=document.createElement('p');status.textContent=completed.length+' / 365 jours validés dans cette version. '+(next?'Prochaine journée non validée : '+next+'.':'Les 365 journées sont validées.');section.append(title,status);const a=document.createElement('a');a.href=url+'#jour-'+(next||last);a.className='choose';a.textContent=next?'Reprendre au jour '+next:'Ouvrir mon parcours';section.append(a);const recent=document.createElement('a');recent.href=url+'#jour-'+last;recent.textContent='Dernière journée ouverte : '+last;section.append(recent);const m=companion?.bookmark;if(m&&Number.isInteger(m.day)&&m.day>=1&&m.day<=365&&typeof m.id==='string'&&marks?.[m.id]){const mark=document.createElement('a');mark.href=url+'#jour-'+m.day;mark.textContent='Retrouver mon dernier repère de lecture — jour '+m.day;section.append(mark)}const note=document.createElement('p');note.textContent='Les autres parcours restent disponibles ci-dessous. Le calendrier personnalisé et le retour au repère se trouvent dans votre parcours.';section.append(note)}
document.getElementById('homeVersion').addEventListener('change',refresh);refresh();
})();
