(()=>{
'use strict';
const form=document.getElementById('planGuide');if(!form)return;
const plans={classique:['Plan avec thèmes','Des lectures et des rapprochements entre les Testaments pour accompagner la réflexion.'],genres:['Lecture par genres','Quatre genres chaque jour : récit, sagesse, prophète et Nouveau Testament.'],salut:['Histoire du salut','Les lectures suivent une progression en douze étapes de la création à la nouvelle création.'],semaines:['Semaines thématiques','Un thème dominant par semaine, avec des passages complémentaires pour l’étude.'],chronologique:['Lecture chronologique','Des rapprochements par grandes périodes ; les placements incertains sont signalés.'],parallele:['Ancien et Nouveau Testament en parallèle','Lire les deux Testaments chaque jour, dans l’ordre des livres.'],rattrapage:['Lecture avec jour de rattrapage','Six journées prévues puis une journée libre ; toute la Bible reste au programme.'],famille:['En famille ou petit groupe','Une lecture personnelle intégrale et un court passage pour le temps partagé.'],continuite:['Lecture avec continuité','Chapitres entiers et certains ensembles conservés sur une journée ; longueurs variables.']};
plans['israel-nations']=["Israël et les nations : un seul peuple en Christ",'Création, alliances, Messie et accueil des nations ; une lecture sans substitution à Israël.'];
plans.connexions=['Connexions bibliques : AT ↔ NT','24 séances approfondies, à rythme libre ; citations et échos distingués.'];
plans.reseau=['La Bible en réseau','200 séances en 50 dossiers pour étudier des chaînes de textes à rythme libre.'];
const goals={reseau:['reseau','connexions'],connexions:['connexions','classique'],israel:['israel-nations','salut'],histoire:['salut','chronologique'],variete:['genres','parallele'],etude:['semaines','classique'],famille:['famille','semaines'],souplesse:['rattrapage','parallele'],continuite:['continuite','salut'],simple:['parallele','classique']};
const picker=document.getElementById('guideVersion');try{const saved=localStorage.getItem('bible-app-version-v1');if(['s21','lsg','pdv'].includes(saved))picker.value=saved}catch(_){}
function recommend(){const goal=document.getElementById('guideGoal').value,preference=document.getElementById('guidePreference').value,out=document.getElementById('guideResults');out.replaceChildren();if(!goal){document.getElementById('guideStatus').textContent='Choisissez ce qui vous aiderait le plus à lire régulièrement.';return}let selected=[...goals[goal]];if(preference&&plans[preference]&&preference!==selected[0])selected=[selected[0],preference,...selected.slice(1).filter(p=>p!==preference)].slice(0,3);document.getElementById('guideStatus').textContent='Voici '+selected.length+' parcours à comparer selon vos réponses.';selected.forEach((id,i)=>{const card=document.createElement('article');card.className='guide-result';const title=document.createElement('h2');title.textContent=(i===0?'Premier parcours à examiner : ':'Autre possibilité : ')+plans[id][0];const reason=document.createElement('p');reason.textContent=plans[id][1];const a=document.createElement('a');a.className='choose';a.textContent='Ouvrir ce parcours';a.href='./plan-'+id+(picker.value==='s21'?'':'-'+picker.value)+'.html';card.append(title,reason,a);out.append(card)})}
form.onsubmit=e=>{e.preventDefault();recommend()};form.addEventListener('change',recommend);recommend();
})();
