(()=>{
'use strict';
const get=k=>{try{return localStorage.getItem(k)}catch(_){return null}},put=(k,v)=>{try{localStorage.setItem(k,v);return true}catch(_){return false}},node=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e};
// Only non-sensitive open/closed preferences are remembered, never the menu or dialogs.
const memoryKey='bible-open-sections-v1-'+(location.pathname.split('/').pop()||'index.html');let memory={};try{memory=JSON.parse(get(memoryKey)||'{}')||{}}catch(_){}
function remember(root=document){root.querySelectorAll('details[id]').forEach(d=>{if(d.dataset.remembered||['appMenu','installationInstructions','importPreview'].includes(d.id)||d.closest('dialog'))return;d.dataset.remembered='yes';const explicit=['outils','sauvegarder','recuperer','choisir','misesajour'].some(k=>new URLSearchParams(location.search).has(k));if(!explicit&&typeof memory[d.id]==='boolean')d.open=memory[d.id];d.addEventListener('toggle',()=>{memory[d.id]=d.open;put(memoryKey,JSON.stringify(memory))})})}
const groups=[
 {books:['GEN'],title:'Création et patriarches',text:'La Genèse raconte les origines puis les familles d’Abraham, d’Isaac et de Jacob. Observez la progression des récits, les promesses et la manière dont Dieu agit au milieu des décisions humaines.',question:'À quel moment du récit suis-je, et à qui la parole est-elle adressée ?'},
 {books:['EXO','LEV','NUM','DEU'],title:'Exode, alliance et vie d’Israël',text:'Ces livres relient la délivrance d’Égypte, l’alliance et la vie du peuple d’Israël. Les lois s’inscrivent dans ce contexte : distinguez leurs destinataires initiaux des applications proposées aujourd’hui.',question:'Comment ce passage relie-t-il la présence de Dieu, la sainteté et la vie communautaire ?'},
 {books:['JOS','JDG','RUT','1SA','2SA','1KI','2KI','1CH','2CH','EZR','NEH','EST'],title:'Israël dans l’histoire',text:'Entrée dans le pays, juges, royauté, exil et retour constituent plusieurs périodes. Repérez les personnages, le lieu et la situation du peuple. Un comportement raconté n’est pas nécessairement un exemple à reproduire.',question:'Quelle situation éclaire les choix des personnages et leurs conséquences ?'},
 {books:['JOB','PSA','PRO','ECC','SNG'],title:'Prière, poésie et sagesse',text:'Poèmes, prières et réflexion sur la vie prennent des formes variées. Dans Job, identifiez celui qui parle ; dans les Psaumes, distinguez lamentation, confiance et louange. Lisez les proverbes comme des paroles de sagesse dans leur contexte.',question:'Qui parle, quel sentiment est exprimé, et quelle sagesse le passage invite-t-il à rechercher ?'},
 {books:['ISA','JER','LAM','EZK','DAN','HOS','JOL','AMO','OBA','JON','MIC','NAM','HAB','ZEP','HAG','ZEC','MAL'],title:'Les prophètes : appel et espérance',text:'Les prophètes s’adressent à des peuples et à des situations précises, souvent à Israël et à Juda. Identifiez l’appel à revenir à Dieu, le jugement et l’espérance. Les rapprochements avec le Nouveau Testament demandent une lecture attentive de leurs deux contextes.',question:'À qui ce message est-il adressé, et quelle réponse est attendue ?'},
 {books:['MAT','MRK','LUK','JHN'],title:'Les Évangiles : suivre Jésus',text:'Les quatre Évangiles présentent la vie, l’enseignement, la mort et la résurrection de Jésus. Repérez ses interlocuteurs et le mouvement du récit. Comparez les passages parallèles en respectant la perspective de chaque Évangile.',question:'Que révèle ce passage sur Jésus, et à quelle réponse appelle-t-il ses interlocuteurs ?'},
 {books:['ACT'],title:'Actes : témoins et mission',text:'Les Actes racontent la progression du témoignage rendu à Jésus, de Jérusalem vers les nations. Observez la place du Saint-Esprit, de la prière, du discernement et de la communauté. Une situation racontée demande à être comprise avant d’être appliquée.',question:'Comment ce récit relie-t-il témoignage, service et accueil des personnes ?'},
 {books:['ROM','1CO','2CO','GAL','EPH','PHP','COL','1TH','2TH','1TI','2TI','TIT','PHM','HEB','JAS','1PE','2PE','1JN','2JN','3JN','JUD'],title:'Les épîtres : foi et vie commune',text:'Ces lettres répondent aux besoins de communautés et de personnes concrètes. Suivez l’argument de l’auteur, ses encouragements et ses exhortations. Les croyants juifs et non juifs sont accueillis en Christ ; les textes concernant Israël gardent leurs destinataires et leur contexte.',question:'Quel besoin de ses destinataires l’auteur traite-t-il, et quel lien fait-il entre foi et conduite ?'},
 {books:['REV'],title:'Apocalypse : fidélité et espérance',text:'L’Apocalypse s’adresse d’abord à des Églises nommées et utilise des visions riches en échos bibliques. Repérez l’appel à la fidélité à Jésus et l’espérance de la nouvelle création. Distinguez les images du texte des interprétations proposées.',question:'Quelle fidélité ce passage encourage-t-il, et comment nourrit-il l’espérance ?'}
];
const path=location.pathname.split('/').pop(),match=path.match(/^plan-(.+?)(?:-(lsg|pdv))?\.html$/),study=match&&['connexions','reseau'].includes(match[1]);
let data=null;if(match){try{data=JSON.parse(document.getElementById(study?'connectionsData':'plan').textContent)}catch(_){}}
if(data){
 const items=study?data.sessions:data,v=match[2]||'s21',prefix=study?'bible-'+match[1]+'-'+v+'-v1':match[1]==='classique'&&v==='s21'?'bible-plan':'bible-'+match[1]+(v==='s21'?'':'-'+v)+'-v1';
 const panel=node('section');panel.id='readingAids';panel.className='reading-aids';const duration=node('p');duration.id='readingDuration';const context=node('details');context.id='stageIntroduction';context.append(node('summary','Situer cette lecture : contexte et questions'));const contextBody=node('div');context.append(contextBody);const weekly=node('details');weekly.id='weeklyReadingReview';weekly.append(node('summary',study?'Bilan de sept séances':'Bilan de ma semaine de lecture'));const weekBody=node('div');weekly.append(weekBody);panel.append(duration,context,weekly);document.getElementById(study?'sessionContent':'content').after(panel);
 function chapter(e){if(e.book&&Number.isInteger(e.chapter))return {book:e.book,n:e.chapter};const m=((e.textPage||'')+' '+(e.page||'')).match(/\/([1-3]?[A-Z]{2,3})\.(\d+)\./);return m?{book:m[1],n:Number(m[2])}:null}
 function refresh(){const n=Number(document.getElementById(study?'sessionSelect':'daySelect').value),d=items[n-1];if(!d)return;const entries=study?d.chapters:d.cards.flatMap(c=>c.entries.map(e=>({...e,cardRef:c.ref,one:c.entries.length===1}))),chapters=new Map();let written=0;const used=new Set();for(const e of entries){const c=chapter(e);if(!c)continue;const count=window.bibleVerseCounts?.[v]?.[c.book]?.[c.n];if(!count)continue;chapters.set(c.book+'.'+c.n,count);let first=e.firstVerse||1,last=e.lastVerse||count;if(!e.firstVerse&&e.one){const range=e.cardRef?.match(/(\d+)[.:](\d+)(?:[–-](\d+))?$/);if(range&&Number(range[1])===c.n){first=Number(range[2]);last=Number(range[3]||range[2])}}const id=c.book+'.'+c.n+':'+first+'-'+last;if(!used.has(id)){used.add(id);written+=Math.max(0,Math.min(count,last)-first+1)}}const full=[...chapters.values()].reduce((a,b)=>a+b,0),speed=Number(document.getElementById('audioSpeed')?.value)||1,minutes=(count,seconds)=>Math.max(1,Math.round(count*seconds/60));duration.textContent=written?'Durée indicative : lecture '+minutes(written,5)+'–'+minutes(written,10)+' min ; écoute des chapitres entiers '+minutes(full,6/speed)+'–'+minutes(full,12/speed)+' min à '+speed+'×.':'';duration.title='Estimation : 5 à 10 secondes par verset pour la lecture et 6 à 12 pour l’audio à vitesse normale. Les extraits non balisés sont estimés comme chapitres entiers. Les durées réelles varient selon le texte et le lecteur.';
 contextBody.replaceChildren(node('p','Repères éditoriaux pour entrer dans le texte. Ils accompagnent sa lecture et ne remplacent pas son contexte ni une étude approfondie.'));if(study&&d.module)contextBody.append(node('h3',d.module));const books=[...chapters.keys()].map(k=>k.split('.')[0]);for(const g of groups.filter(g=>g.books.some(b=>books.includes(b)))){contextBody.append(node('h3',g.title),node('p',g.text),node('p','À observer : '+g.question))}contextBody.append(node('p','Commencez par les références proposées, puis observez le passage, son contexte et les destinataires avant de formuler une application.'));
 let marks=[],notes={};try{if(study){const s=JSON.parse(get(prefix+'-state')||'{}');marks=s.completedDays||[];notes=s.notes||{}}else{marks=JSON.parse(get(prefix+'-completed-days-v1')||'[]');notes=JSON.parse(get(prefix+'-notes-v1')||'{}')}}catch(_){}if(!Array.isArray(marks))marks=[];if(!notes||typeof notes!=='object')notes={};const start=Math.floor((n-1)/7)*7+1,end=Math.min(items.length,start+6),range=Array.from({length:end-start+1},(_,i)=>start+i),done=range.filter(i=>marks.includes(i));weekBody.replaceChildren(node('p',(study?'Séances ':'Jours ')+start+' à '+end+' : '+done.length+' / '+range.length+' validés. Ce bilan suit les étapes du parcours, pas les dates de vos validations.'),node('p','Avancez à votre rythme. Une lecture à reprendre peut aussi être une occasion de relire ou de méditer.'));for(const [label,list] of [['À reprendre',range.filter(i=>!marks.includes(i))],['Notes à relire',range.filter(i=>typeof notes[i]==='string'&&notes[i].trim())]]){weekBody.append(node('h3',label));if(!list.length)weekBody.append(node('p',label==='À reprendre'?'Toutes les étapes de ce groupe sont validées.':'Aucune note dans ce groupe.'));for(const i of list){const a=node('a',(study?'Séance ':'Jour ')+i+' — '+(items[i-1].title||items[i-1].theme));a.href='./'+path+'#'+(study?'seance-':'jour-')+i;a.onclick=e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();const select=document.getElementById(study?'sessionSelect':'daySelect');select.value=String(i);select.dispatchEvent(new Event('change',{bubbles:true}));const target=document.getElementById(label==='Notes à relire'?(study?'sessionNotes':'dailyNotes'):(study?'sessionContent':'content'));if(target){for(let parent=target;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;target.scrollIntoView({block:'start'});if(label==='Notes à relire')target.focus()}};weekBody.append(a)}}}
 refresh();new MutationObserver(refresh).observe(document.getElementById(study?'sessionContent':'content'),{childList:true});document.addEventListener('change',refresh);let timeout;document.addEventListener('input',e=>{if(['dailyNotes','sessionNotes'].includes(e.target.id)){clearTimeout(timeout);timeout=setTimeout(refresh,700)}});
 if(new URLSearchParams(location.search).get('recuperer')==='1'){document.getElementById('dismissStartGuide')?.click();const guide=node('section');guide.id='recoveryDestination';guide.className='reading-aids';guide.append(node('h2','Récupérer ce parcours'),node('p',study?'Choisissez votre fichier dans le contrôle d’import. Pour un fichier protégé, saisissez d’abord sa phrase secrète. Le résumé apparaît avant toute modification. Ces parcours remplacent le suivi après confirmation : sauvegardez le suivi actuel auparavant.':'Commencez par contrôler votre fichier, sans import ni modification. Saisissez sa phrase secrète s’il est protégé, puis comparez le résumé. Lancez ensuite l’import et examinez les choix de fusion et les notes différentes avant de confirmer.'),node('p','Après import, vérifiez les coches et deux ou trois notes. Une sauvegarde ne réunit pas automatiquement les autres plans ou versions.'));const target=document.getElementById(study?'importConnections':'chooseBackupCheck');if(target){for(let e=target;e;e=e.parentElement)if(e.tagName==='DETAILS')e.open=true;target.closest('section,details')?.before(guide);target.scrollIntoView({block:'center'});target.focus()}else panel.after(guide)}
}
if(path==='recuperer-suivi.html'){
 const box=node('section');box.id='recoveryWizard';box.className='reading-aids';box.append(node('h2','Récupération guidée'),node('p','1. Retrouvez le fichier JSON exporté et, s’il est protégé, sa phrase secrète. 2. Choisissez son parcours et sa traduction. 3. Contrôlez son résumé avant d’importer. 4. Vérifiez les coches et quelques notes après l’import.'));
 const plan=node('select');plan.id='recoveryPlan';plan.append(new Option('Choisir le parcours du fichier',''));const labels=['Plan avec thèmes','Lecture par genres','Histoire du salut','Semaines thématiques','Lecture chronologique','AT et NT en parallèle','Lecture avec rattrapage','En famille ou petit groupe','Lecture avec continuité','Israël et les nations','Connexions AT ↔ NT (24 séances)','La Bible en réseau (200 séances)'];const ids=['classique','genres','salut','semaines','chronologique','parallele','rattrapage','famille','continuite','israel-nations','connexions','reseau'];ids.forEach((id,i)=>plan.add(new Option(labels[i],id)));const version=node('select');version.id='recoveryVersion';version.append(new Option('Choisir la traduction du fichier',''),new Option('Segond 21','s21'),new Option('Segond — Trésor Sonore','lsg'),new Option('Parole de Vie 2017','pdv'));for(const [id,text,field] of [['recoveryPlan','Parcours à récupérer',plan],['recoveryVersion','Traduction à récupérer',version]]){const label=node('label',text);label.htmlFor=id;box.append(label,field)}const have=node('input');have.type='checkbox';have.id='recoveryHasFile';const label=node('label');label.append(have,document.createTextNode(' J’ai le fichier de sauvegarde et sa phrase secrète, si nécessaire.'));const go=node('a','Continuer vers le contrôle du fichier');go.id='recoveryContinue';go.hidden=true;const hint=node('p','Si le fichier manque, exportez d’abord votre suivi depuis l’ancien appareil. Cette page ne récupère pas des données effacées sans sauvegarde.');hint.id='recoveryHint';function update(){go.hidden=!(plan.value&&version.value&&have.checked);if(!go.hidden){go.href='./plan-'+plan.value+(version.value==='s21'?'':'-'+version.value)+'.html?recuperer=1';hint.textContent=['connexions','reseau'].includes(plan.value)?'Ce parcours contrôle le fichier dans l’aperçu d’import et remplace le suivi après confirmation. Sauvegardez le suivi actuel auparavant.':'Le contrôle du fichier est sans modification du suivi. L’import vous proposera ensuite ses choix de fusion.'}}plan.onchange=version.onchange=have.onchange=update;box.append(label,hint,go);document.querySelector('main h1').after(box);
}
function verses(){const box=document.getElementById('dailyVerse'),library=window.bibleDailyVerseLibrary,current=window.bibleDailyVerseCurrent;if(!box||!library||!current||box.querySelector('#versePractice'))return;let refs=[];try{const stored=JSON.parse(get('bible-verse-favorites-v1')||'[]');if(Array.isArray(stored))refs=[...new Set(stored.filter(r=>library.some(v=>v.ref===r)))]}catch(_){}const area=node('section');area.id='versePractice';area.className='reading-aids';const hide=node('button','Masquer le texte pour le réciter');hide.type='button';hide.setAttribute('aria-controls','dailyVerseQuotation');box.querySelector('blockquote').id='dailyVerseQuotation';hide.setAttribute('aria-expanded','true');hide.onclick=()=>{const quote=box.querySelector('blockquote');quote.hidden=!quote.hidden;hide.textContent=quote.hidden?'Révéler le verset':'Masquer le texte pour le réciter';hide.setAttribute('aria-expanded',String(!quote.hidden))};const favorite=node('button');favorite.type='button';const status=node('p');status.id='verseFavoritesStatus';status.setAttribute('role','status');const detail=node('details');detail.id='verseFavorites';detail.append(node('summary','Mes versets favoris'));const list=node('div');detail.append(list);const exportButton=node('button','Exporter mes versets favoris');exportButton.type='button';const input=node('input');input.id='verseFavoritesFile';input.type='file';input.accept='.json,application/json';const label=node('label','Récupérer un fichier de versets favoris');label.htmlFor=input.id;const preview=node('p');preview.id='verseFavoritesPreview';const confirm=node('button','Remplacer mes favoris par cette sélection');confirm.type='button';confirm.hidden=true;const cancel=node('button','Annuler');cancel.type='button';cancel.hidden=true;let pending=null;
 function refresh(){favorite.textContent=refs.includes(current.ref)?'Retirer ce verset de mes favoris':'Garder ce verset dans mes favoris';favorite.setAttribute('aria-pressed',String(refs.includes(current.ref)));list.replaceChildren();for(const ref of refs){const verse=library.find(v=>v.ref===ref),p=node('p',ref+' — '+verse.text),a=node('a','Lire le chapitre');a.href='https://www.bible.com/bible/93/'+verse.book+'.'+verse.chapter+'.LSG';p.append(a);list.append(p)}if(!refs.length)list.append(node('p','Aucun favori pour le moment.'));exportButton.disabled=!refs.length}
 function persist(){if(!put('bible-verse-favorites-v1',JSON.stringify(refs)))status.textContent='Les favoris restent disponibles pendant cette visite. Exportez-les pour les conserver.';refresh()}
 favorite.onclick=()=>{refs=refs.includes(current.ref)?refs.filter(r=>r!==current.ref):[...refs,current.ref];persist()};exportButton.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({format:'bible-versets-favoris',version:1,references:refs},null,2)],{type:'application/json'})),a=node('a');a.href=url;a.download='versets-favoris.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Fichier de favoris préparé. Ce fichier ne remplace pas la sauvegarde de votre parcours.'};input.onchange=async()=>{pending=null;confirm.hidden=cancel.hidden=true;try{const f=input.files[0];if(!f)return;if(f.size>100000)throw Error();const d=JSON.parse(await f.text());if(d.format!=='bible-versets-favoris'||d.version!==1||!Array.isArray(d.references)||d.references.length>library.length||!d.references.every(r=>typeof r==='string'&&library.some(v=>v.ref===r)))throw Error();pending=[...new Set(d.references)];preview.textContent=pending.length+' favoris vérifiés. La sélection actuelle sera remplacée uniquement après confirmation.';confirm.hidden=cancel.hidden=false}catch(_){preview.textContent='Fichier de favoris invalide. Votre sélection est conservée.'}finally{input.value=''}};confirm.onclick=()=>{if(!pending)return;refs=pending;pending=null;persist();confirm.hidden=cancel.hidden=true;preview.textContent='Favoris récupérés.'};cancel.onclick=()=>{pending=null;confirm.hidden=cancel.hidden=true;preview.textContent='Import annulé. Favoris conservés.'};detail.append(exportButton,label,input,preview,confirm,cancel);area.append(hide,favorite,status,detail,node('p','Les favoris sont enregistrés sur cet appareil. Exportez cette sélection pour la transférer ; la sauvegarde d’un parcours ne contient pas ces favoris.'));box.append(area);refresh();remember(area)}
verses();window.addEventListener('bible-daily-verse-changed',verses);remember();
})();
