(()=>{
const panel=document.getElementById('calendarPanel');if(!panel)return;
const timeInput=document.getElementById('calendarTime'),range=document.getElementById('calendarRange'),status=document.getElementById('calendarStatus'),exportButton=document.getElementById('exportCalendar');
const key='bible-calendar-v1-'+location.pathname.split('/').pop();const weekdays=['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];const order=[1,2,3,4,5,6,0];
function validTime(t){return typeof t==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(t)}
function validSettings(s){return s&&Array.isArray(s.week)&&s.week.length===7&&s.week.every(r=>r&&typeof r.enabled==='boolean'&&validTime(r.time))&&s.exceptions&&typeof s.exceptions==='object'&&!Array.isArray(s.exceptions)&&Object.keys(s.exceptions).length<=1000&&Object.entries(s.exceptions).every(([date,r])=>/^\d{4}-\d\d-\d\d$/.test(date)&&validStartDate(date)&&r&&typeof r.enabled==='boolean'&&validTime(r.time))}
let settings={week:weekdays.map(()=>({enabled:true,time:validTime(timeInput.value)?timeInput.value:'08:00'})),exceptions:{}};
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(validSettings(saved))settings=saved}catch(_){}
function persist(){try{localStorage.setItem(key,JSON.stringify(settings));status.textContent='Réglages des rappels enregistrés sur cet appareil.'}catch(_){status.textContent='Sauvegarde locale impossible. Gardez cette page ouverte pour exporter vos rappels.'}}
const intro=panel.querySelector('p');intro.textContent='Choisissez les horaires habituels, puis adaptez les dates à votre travail ou à vos congés. Une coche active le rendez-vous et son alerte ; elle ne valide pas votre lecture. Exportez ensuite le fichier et importez-le dans votre calendrier. Les heures suivent le fuseau horaire de votre calendrier ; les alertes dépendent de ses réglages.';
const apply=document.createElement('button');apply.type='button';apply.id='calendarApplyTime';apply.textContent='Appliquer cette heure à toute la semaine';timeInput.after(apply);
const weekly=document.createElement('div');weekly.id='calendarWeekly';weekly.className='calendar-flexible';const heading=document.createElement('h3');heading.textContent='Mon planning habituel';weekly.append(heading);
const weeklyInputs=[];
for(const index of order){const row=document.createElement('div');row.className='calendar-reminder-row';const label=document.createElement('label'),check=document.createElement('input'),text=document.createElement('span'),time=document.createElement('input');check.type='checkbox';check.checked=settings.week[index].enabled;check.dataset.weekday=index;check.setAttribute('aria-label','Activer le rappel du '+weekdays[index].toLowerCase());text.textContent=weekdays[index];label.append(check,text);time.type='time';time.value=settings.week[index].time;time.dataset.weektime=index;time.setAttribute('aria-label','Heure du '+weekdays[index].toLowerCase());time.disabled=!check.checked;weeklyInputs[index]={check,time};check.onchange=()=>{settings.week[index].enabled=check.checked;time.disabled=!check.checked;persist();renderDates()};time.onchange=()=>{if(!validTime(time.value)){status.textContent='Choisissez une heure valide.';return}settings.week[index].time=time.value;persist();renderDates()};row.append(label,time);weekly.append(row)}
apply.onclick=()=>{if(!validTime(timeInput.value)){status.textContent='Choisissez une heure valide.';return}settings.week.forEach((r,i)=>{r.time=timeInput.value;weeklyInputs[i].time.value=r.time});persist();renderDates()};
const specific=document.createElement('details');specific.id='calendarExceptions';const summary=document.createElement('summary');summary.textContent='Adapter chaque date : travail, congés…';const description=document.createElement('p');description.textContent='Une modification ici remplace le planning habituel pour cette date. « Habituel » efface cette exception. Décochez une date pour ne pas exporter de rappel ce jour-là.';
const pickerLabel=document.createElement('label');pickerLabel.textContent='Mois à afficher';const picker=document.createElement('select');picker.id='calendarMonth';picker.setAttribute('aria-label','Mois des rappels');pickerLabel.append(picker);const dates=document.createElement('div');dates.id='calendarDates';const dateMessage=document.createElement('p');dateMessage.id='calendarDatesStatus';dateMessage.setAttribute('role','status');specific.append(summary,description,pickerLabel,dateMessage,dates);range.before(weekly,specific);
const note=document.createElement('p');note.textContent='Modifier ces réglages ne change pas les événements déjà importés. Réexportez ensuite le fichier ; selon votre calendrier, une nouvelle importation peut créer des doublons. Utilisez de préférence un calendrier séparé pour vos rappels de lecture. Ces réglages sont propres à ce plan et à cette version ; ils sont inclus dans sa sauvegarde.';
exportButton.after(note);let lastStart='';
function iso(n){const personal=window.dailyCompanion?.dateFor(n);if(window.dailyCompanion?.enabled())return personal;return new Date((dateNumber(startDateValue)+n-1)*86400000).toISOString().slice(0,10)}
function effective(date){return settings.exceptions[date]||settings.week[new Date(date+'T12:00:00Z').getUTCDay()]}
function renderDates(){if(window.dailyCompanion?.enabled()&&!window.dailyCompanion.dateFor(365)){picker.replaceChildren();dates.replaceChildren();dateMessage.textContent='Appliquez un rythme avec des dates disponibles avant de préparer les rappels.';return}
 if(!validStartDate(startDateValue)){picker.replaceChildren();dates.replaceChildren();dateMessage.textContent='Définissez votre date de départ dans « Calendrier personnel » pour afficher les dates.';lastStart='';return}
 const all=days.map((_,i)=>({n:i+1,date:iso(i+1)})),months=[...new Set(all.map(r=>r.date.slice(0,7)))],old=picker.value;
 picker.replaceChildren();for(const month of months){const o=document.createElement('option');o.value=month;o.textContent=new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(month+'-01T12:00:00Z'));picker.append(o)}
 const today=new Date().toLocaleDateString('sv-SE').slice(0,7);picker.value=months.includes(old)?old:months.includes(today)?today:months[0];lastStart=startDateValue;dates.replaceChildren();
 const rows=all.filter(r=>r.date.startsWith(picker.value));dateMessage.textContent=rows.length+' dates affichées. Les autres mois conservent leurs réglages.';
 for(const {n,date} of rows){const r=effective(date),row=document.createElement('div');row.className='calendar-reminder-row calendar-date-row';row.dataset.date=date;const label=document.createElement('label'),check=document.createElement('input'),text=document.createElement('span'),time=document.createElement('input'),reset=document.createElement('button');check.type='checkbox';check.checked=r.enabled;check.setAttribute('aria-label','Activer le rappel du '+date);text.textContent=new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'))+' · Jour '+n+(settings.exceptions[date]?' · personnalisé':'');label.append(check,text);time.type='time';time.value=r.time;time.disabled=!r.enabled;time.setAttribute('aria-label','Heure du rappel du '+date);reset.type='button';reset.textContent='Habituel';reset.disabled=!settings.exceptions[date];reset.setAttribute('aria-label','Rétablir le planning habituel du '+date);
 function save(){if(!validTime(time.value)){status.textContent='Choisissez une heure valide.';return}settings.exceptions[date]={enabled:check.checked,time:time.value};persist();renderDates()}
 check.onchange=save;time.onchange=save;reset.onclick=()=>{delete settings.exceptions[date];persist();renderDates()};row.append(label,time,reset);dates.append(row)}
}
picker.onchange=renderDates;panel.addEventListener('toggle',()=>{if(panel.open)renderDates()});document.getElementById('startDate')?.addEventListener('change',()=>setTimeout(renderDates,0));
new MutationObserver(()=>{if(lastStart!==startDateValue&&panel.open)renderDates()}).observe(document.getElementById('content'),{childList:true});renderDates();
window.calendarReminders={refresh:renderDates,snapshot:()=>JSON.parse(JSON.stringify(settings)),valid:validSettings,restore:s=>{if(validSettings(s)){settings=JSON.parse(JSON.stringify(s));settings.week.forEach((r,i)=>{weeklyInputs[i].check.checked=r.enabled;weeklyInputs[i].time.value=r.time;weeklyInputs[i].time.disabled=!r.enabled});persist();renderDates()}}};
exportButton.onclick=()=>{if(window.dailyCompanion?.enabled()&&!window.dailyCompanion.dateFor(365)){status.textContent='Votre rythme personnel ne contient pas de calendrier valide. Choisissez des jours disponibles.';return}
 if(!validStartDate(startDateValue)){status.textContent='Définissez d’abord votre date de départ dans « Calendrier personnel ».';return}
 if(settings.week.some(r=>!validTime(r.time))){status.textContent='Choisissez des heures valides.';return}
 const list=days.map((_,i)=>i+1).filter(n=>(range.value==='all'||!completed.has(n))&&effective(iso(n)).enabled);
 if(!list.length){status.textContent='Aucun rappel activé dans les jours à exporter.';return}
 const stamp=new Date().toISOString().slice(0,19).replace(/[-:]/g,'')+'Z',lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Plan Biblique//Lecture quotidienne//FR','CALSCALE:GREGORIAN','METHOD:PUBLISH'];
 const plan=location.pathname.split('/').pop().replace('.html','');
 for(const n of list){const date=iso(n),time=effective(date).time,start=date.replace(/-/g,'')+'T'+time.replace(':','')+'00',end=new Date(Date.parse(date+'T'+time+':00Z')+15*60000).toISOString().replace(/[-:]/g,'').slice(0,15),d=days[n-1],url='https://jeannoeldoux.github.io/Plan-Biblique-lecture-en-1-an/'+plan+'.html#jour-'+n;
 lines.push('BEGIN:VEVENT','UID:lecture-'+plan+'-'+startDateValue+'-'+n+'@plan-biblique.local','DTSTAMP:'+stamp,'DTSTART:'+start,'DTEND:'+end,'SUMMARY:'+calendarEscape('Lecture biblique — Jour '+n+' : '+d.theme),'DESCRIPTION:'+calendarEscape(d.cards.map(c=>c.label+' : '+c.ref).join('\n')+'\nOuvrir le plan : '+url),'BEGIN:VALARM','ACTION:DISPLAY','TRIGGER:PT0S','DESCRIPTION:'+calendarEscape('Lecture biblique — Jour '+n),'END:VALARM','END:VEVENT')}
 lines.push('END:VCALENDAR');const output=lines.map(foldCalendarLine).join('\r\n')+'\r\n',url=URL.createObjectURL(new Blob([output],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='rappels-'+plan+'-'+startDateValue+'.ics';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent=list.length+' rappels activés préparés avec leurs horaires. Importez le fichier dans votre calendrier.';
};
})();