(()=>{
'use strict';
const q=document.getElementById('query'),pf=document.getElementById('planFilter'),vf=document.getElementById('versionFilter'),results=document.getElementById('results'),status=document.getElementById('resultStatus'),more=document.getElementById('more');
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[.,:;–—-]/g,' ').replace(/\s+/g,' ').trim();
let loading=null,indexed=null,matches=[],shown=0,timer,revision=0;
function load(){if(indexed)return Promise.resolve(indexed);if(loading)return loading;loading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='./search-index.js';script.onload=()=>{try{const d=window.bibleSearchData;if(!d||!Array.isArray(d.rows))throw Error();indexed=d.rows.map(([pi,vi,jour,ti,ri])=>{const [plan,label]=d.plans[pi],version=d.versions[vi],theme=d.themes[ti],references=d.references[ri],study=['connexions','reseau'].includes(plan);return {plan,label,version,jour,theme,references,url:'plan-'+plan+(version==='s21'?'':'-'+version)+'.html#'+(study?'seance-':'jour-')+jour,text:norm(theme+' '+references+(study?' seance ':' jour ')+jour)}});delete window.bibleSearchData;resolve(indexed)}catch(_){indexed=null;loading=null;script.remove();reject(Error('index'))}};script.onerror=()=>{loading=null;script.remove();reject(Error('network'))};document.head.append(script)});return loading}
function el(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
function append(){const fragment=document.createDocumentFragment();for(const r of matches.slice(shown,shown+20)){const study=['connexions','reseau'].includes(r.plan),card=el('article',''),title=el('h2',(study?'Séance ':'Jour ')+r.jour+' — '+r.theme),info=el('small',r.label+' · '+(r.version==='s21'?'Segond 21':r.version==='pdv'?'Parole de Vie 2017':'Segond 1910 — Trésor Sonore')),refs=el('p',r.references),link=el('a',study?'Ouvrir cette séance':'Ouvrir cette journée');link.className='open';link.href='./'+r.url;card.append(title,info,refs,link);fragment.append(card)}shown=Math.min(shown+20,matches.length);results.append(fragment);more.hidden=shown>=matches.length}
async function search(){const request=++revision,words=norm(q.value).split(' ').filter(Boolean),plan=pf.value,version=vf.value;results.replaceChildren();shown=0;more.hidden=true;if(!words.length){status.textContent='Saisissez un livre, une référence ou un thème pour commencer.';return}status.textContent='Préparation de la recherche…';try{const data=await load();if(request!==revision)return;matches=data.filter(r=>(!plan||r.plan===plan)&&(!version||r.version===version)&&words.every(w=>r.text.includes(w)));status.textContent=matches.length?matches.length+' lecture'+(matches.length>1?'s':'')+' trouvée'+(matches.length>1?'s':'')+'.':'Aucune lecture trouvée. Essayez le nom du livre ou un thème plus général.';append()}catch(_){if(request===revision)status.textContent='La recherche n’a pas pu être chargée. Connectez-vous une première fois pour la préparer, puis relancez votre recherche.'}}
document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();clearTimeout(timer);search()};q.oninput=()=>{clearTimeout(timer);++revision;timer=setTimeout(search,180)};pf.onchange=vf.onchange=()=>{clearTimeout(timer);search()};more.onclick=append;
const params=new URLSearchParams(location.search);if(params.get('q'))q.value=params.get('q');search();
})();
