(()=>{
const FORMAT='bible-backup-encrypted',ITERATIONS=600000,MAX=16000000,AAD=new TextEncoder().encode('BibleBackup-v1');
function available(){return !!globalThis.crypto?.subtle}
function b64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)}
function bytes(s){if(typeof s!=='string'||s.length>22000000||!/^[A-Za-z0-9+/]*={0,2}$/.test(s))throw Error('format');return Uint8Array.from(atob(s),x=>x.charCodeAt(0))}
async function key(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password.normalize('NFC')),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:ITERATIONS,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptData(data,password){if(!available())throw Error('unsupported');if(password.length<12||password.length>1024)throw Error('password');const raw=new TextEncoder().encode(JSON.stringify(data));if(raw.length>MAX)throw Error('size');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:AAD,tagLength:128},await key(password,salt),raw);return {format:FORMAT,version:1,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(cipher))}}
function validateEnvelope(e){if(!e||e.format!==FORMAT||e.version!==1||e.kdf!=='PBKDF2-SHA256'||e.iterations!==ITERATIONS||e.cipher!=='AES-256-GCM')throw Error('format');const salt=bytes(e.salt),iv=bytes(e.iv),cipher=bytes(e.data);if(salt.length!==16||iv.length!==12||cipher.length<16||cipher.length>MAX+16)throw Error('size');return {salt,iv,cipher}}
async function decryptEnvelope(e,password){if(!available())throw Error('unsupported');const {salt,iv,cipher}=validateEnvelope(e);if(password.length>1024)throw Error('password');try{const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:AAD,tagLength:128},await key(password,salt),cipher);return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw))}catch(_){throw Error('decrypt')}}
const dialog=document.createElement('dialog');dialog.id='secureBackupDialog';dialog.setAttribute('aria-labelledby','secureBackupTitle');
dialog.innerHTML='<form id="secureBackupForm"><h2 id="secureBackupTitle">Sauvegarde protégée</h2><p id="secureBackupExplanation"></p><label for="backupPassword">Mot de passe ou phrase secrète</label><input id="backupPassword" type="password" maxlength="1024" autocomplete="new-password" required style="display:block;width:100%;min-height:44px"><div id="passwordConfirmation"><label for="backupPasswordConfirm">Confirmer le mot de passe</label><input id="backupPasswordConfirm" type="password" maxlength="1024" autocomplete="new-password" style="display:block;width:100%;min-height:44px"></div><p id="secureBackupError" role="status" aria-live="polite"></p><div class="tracking-actions"><button id="secureBackupConfirm" type="submit">Continuer</button><button id="secureBackupCancel" type="button">Annuler</button></div></form>';
document.body.append(dialog);const form=dialog.querySelector('form'),password=dialog.querySelector('#backupPassword'),confirm=dialog.querySelector('#backupPasswordConfirm'),error=dialog.querySelector('#secureBackupError');
let pending=null;
function finish(value){password.value=confirm.value='';dialog.close();const callback=pending;pending=null;callback?.(value)}
function ask(mode){if(pending)return Promise.reject(Error('busy'));return new Promise(resolve=>{pending=resolve;password.value=confirm.value='';error.textContent='';dialog.querySelector('#secureBackupTitle').textContent=mode==='export'?'Exporter une sauvegarde protégée':'Ouvrir une sauvegarde protégée';dialog.querySelector('#secureBackupExplanation').textContent=mode==='export'?'Choisissez une phrase secrète d’au moins 12 caractères. Elle ne sera pas enregistrée. Sans elle, ce fichier ne pourra pas être récupéré. Le suivi enregistré dans le navigateur n’est pas chiffré par cette option.':'Saisissez le mot de passe utilisé lors de l’export. Aucun mot de passe n’est envoyé ni enregistré. Votre suivi reste inchangé tant que vous n’avez pas confirmé l’import.';dialog.querySelector('#passwordConfirmation').hidden=mode!=='export';confirm.required=mode==='export';password.autocomplete=mode==='export'?'new-password':'current-password';form.onsubmit=e=>{e.preventDefault();if(mode==='export'&&(password.value.length<12||password.value!==confirm.value)){error.textContent=password.value.length<12?'Utilisez au moins 12 caractères.':'Les deux mots de passe sont différents.';return}finish(password.value)};dialog.querySelector('#secureBackupCancel').onclick=()=>finish(null);dialog.oncancel=e=>{e.preventDefault();finish(null)};dialog.showModal();password.focus()})}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
let exporting=false;
async function startExport(){const status=document.getElementById('secureBackupStatus')||document.getElementById('backupStatus');if(exporting)return;if(!available()){if(status)status.textContent='La sauvegarde protégée nécessite un navigateur compatible et une connexion HTTPS, comme GitHub Pages.';return}exporting=true;try{const pw=await ask('export');if(pw===null){if(status)status.textContent='Export annulé. Votre suivi est conservé.';return}const snapshot=createBackupData();if(status)status.textContent='Préparation de la sauvegarde protégée…';const envelope=await encryptData(snapshot,pw);download(envelope,'sauvegarde-bible-protegee-'+new Date().toISOString().slice(0,10)+'.json');recordProtectedBackupExport();if(status)status.textContent='Sauvegarde protégée préparée. Gardez le fichier et son mot de passe en lieu sûr.'}catch(_){if(status)status.textContent='La sauvegarde protégée n’a pas pu être préparée. Votre suivi est conservé.'}finally{exporting=false}}
async function decodeFile(file){if(file.size>32000000)throw Error('size');const data=JSON.parse(await file.text());if(data?.format!==FORMAT){if(file.size>MAX)throw Error('size');return data}validateEnvelope(data);if(!available())throw Error('unsupported');const pw=await ask('decrypt');if(pw===null)throw Error('cancelled');return decryptEnvelope(data,pw)}
window.secureBackup={encryptData,decryptEnvelope,decodeFile,startExport};
if(document.getElementById('exportBackup')){
const panel=document.createElement('section');panel.id='secureBackupPanel';panel.className='planning';panel.innerHTML='<h3>Protéger ma sauvegarde</h3><p>Exportez vos notes et votre progression dans un fichier protégé par mot de passe. Le fichier reste sur votre appareil ; aucune inscription n’est nécessaire.</p><button id="exportProtectedBackup" type="button">Exporter avec mot de passe</button><p id="secureBackupStatus" role="status"></p><p><a href="./recuperer-suivi.html">Comment récupérer mon suivi ?</a></p>';
document.getElementById('exportBackup').before(panel);document.getElementById('exportProtectedBackup').onclick=startExport;document.getElementById('exportBackup').textContent='Exporter sans mot de passe';
const preview=document.getElementById('importPreview');if(preview){const note=document.createElement('p');note.textContent='La copie de sécurité automatique avant import est sans mot de passe. Pour une copie protégée, utilisez d’abord « Exporter avec mot de passe ».';preview.append(note)}
}
})();
