(()=>{
'use strict';
const db=window.bibleStudyData;if(!db)return;
const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e};
const version=location.pathname.includes('-lsg.html')?'lsg':location.pathname.includes('-pdv.html')?'pdv':'s21';
function link(book,ch,lo,hi,v=version){if(v==='lsg')return 'https://www.biblegateway.com/passage/?search='+encodeURIComponent(db.books[book].name+' '+ch+(lo?':'+lo+(hi&&hi!==lo?'-'+hi:''):''))+'&version=LSG';return 'https://www.bible.com/fr/bible/'+(v==='pdv'?'133':'152')+'/'+book+'.'+ch+(lo?'.'+lo+(hi&&hi!==lo?'-'+hi:''):'')+'.'+(v==='pdv'?'PDV2017':'S21')}
function external(text,href){const a=make('a',text);a.href=href;a.target='_blank';a.rel='noopener noreferrer';return a}
function bookOf(e){return e.book||e.page?.match(/\/([A-Z0-9]+)\.\d+/)?.[1]}
function chapterOf(e){return Number(e.chapter||e.page?.match(/\/[A-Z0-9]+\.(\d+)/)?.[1])}
function entries(d,main=false){return d.cards.filter(c=>!main||c.kind!=='mirror').flatMap(c=>c.entries)}
function has(es,b,c,a,z){return es.some(e=>bookOf(e)===b&&chapterOf(e)===c&&(e.firstVerse||1)<=a&&(e.lastVerse||Infinity)>=z)}
function intro(code){const b=db.books[code],box=make('details',null,'book-introduction');box.append(make('summary',b.name+' — introduction'));box.append(make('p',b.genre+' · '+b.stage,'study-caption'),make('p',b.intro),make('p',b.structure),make('p','Question pour le livre : '+b.question));box.append(external('Lire '+b.name+' à partir du chapitre 1',link(code,1)),make('p','Le contexte évoqué est celui du récit ou des destinataires. Il ne suffit pas à dater la rédaction. Ces repères synthétiques sont à confronter au livre entier.','study-caption'));return box}
const content=document.getElementById('content');
function add(){const day=content?.querySelector('.day');if(!day||day.querySelector('.study-resources'))return;const focusedControl=document.activeElement;const d=days[current-1],es=entries(d),main=entries(d,true),codes=[...new Set(main.map(bookOf))].filter(c=>db.books[c]);
const badge=make('p',codes.length?'Repères des lectures : '+[...new Set(codes.map(c=>db.books[c].stage))].join(' · '):'Journée libre : relire, rattraper ou se reposer','study-stage');day.querySelector('.theme')?.after(badge);
const cards=[...day.querySelectorAll('.subcard')];cards.forEach((card,i)=>{const source=d.cards[i],complement=source?.kind==='mirror';card.classList.toggle('study-complement',complement);card.prepend(make('p',complement?'Passage complémentaire — pour rapprocher ou partager':'Lecture du parcours — à lire pour valider cette journée','study-caption'));const audio=card.querySelector('.buttons');if(audio){const reading=make('div',null,'study-written-links');for(const e of source.entries){const b=bookOf(e),ch=chapterOf(e);if(db.books[b]){const row=make('div',null,'study-written-chapter');row.append(external('Lire '+(e.readingRef||e.title),e.textPage||link(b,ch,e.firstVerse,e.lastVerse)));const id=e.page.split('/').pop(),mark=[...audio.querySelectorAll('[data-reading-mark]')].find(button=>button.dataset.readingMark===id);if(mark)row.append(mark);reading.append(row)}}audio.before(reading);const details=make('details',null,'study-audio-options');details.append(make('summary','Écouter et suivre les chapitres'));audio.before(details);details.append(audio)}});
const resources=make('section',null,'study-resources');resources.setAttribute('aria-label','Accompagnement de la lecture');resources.append(make('h2','Pour accompagner la lecture'));
const overview=make('details');overview.append(make('summary','Découvrir les livres du jour'));codes.forEach(c=>overview.append(intro(c)));if(!codes.length)overview.append(make('p','Vous pouvez consulter les introductions des 66 livres.'));const all=make('a','Introductions des 66 livres');all.href='./livres.html';overview.append(all);resources.append(overview);
const questions=make('details');questions.id='passageQuestions';questions.append(make('summary','Observer, comprendre, réfléchir'));const focused=db.questions.filter(q=>has(es,...q.span));
for(const q of focused.slice(0,3)){const box=make('div',null,'passage-question');box.append(make('h3',db.books[q.span[0]].name+' '+q.span[1]+':'+q.span[2]+(q.span[3]!==q.span[2]?'–'+q.span[3]:'')),make('p','Observer : '+q.observe),make('p','Comprendre : '+q.understand),make('p','Réfléchir : '+q.apply),external('Relire les versets concernés',link(...q.span)));questions.append(box)}
if(!focused.length){questions.append(make('p',main.length?'Dans '+d.cards.filter(c=>c.kind!=='mirror'&&c.entries.length).map(c=>c.ref).join(' ; ')+', relevez une parole, un geste ou une image et vérifiez son sens dans le paragraphe qui l’entoure.':'Quel passage aimeriez-vous relire, sans ajouter une obligation pour cette journée ?'));if(codes.length)questions.append(make('p','Pour approfondir '+db.books[codes[0]].name+' : '+db.books[codes[0]].question));questions.append(make('p','Aucune question ciblée sur des versets précis n’est proposée pour cette sélection.','study-caption'))}
questions.append(make('p','Vous pouvez garder une question ouverte ou ne pas partager une expérience personnelle. Les questions ciblées complètent les pistes déjà présentes dans le parcours.','study-caption'));resources.append(questions);
const comparisons=make('details');comparisons.id='documentedLinks';comparisons.append(make('summary','Vérifier les rapprochements bibliques'));const relevant=db.links.filter(r=>has(es,...r.nt)||has(es,...r.ot));
for(const r of relevant){const paired=has(es,...r.nt)&&has(es,...r.ot),box=make('div',null,'documented-link');box.append(make('h3',r.kind+(paired?' — les deux passages sont prévus ce jour':' — référence complémentaire')),make('p',r.explanation));box.append(external(db.books[r.ot[0]].name+' '+r.ot[1]+':'+r.ot[2]+'–'+r.ot[3],link(...r.ot)),document.createTextNode(' · '),external(db.books[r.nt[0]].name+' '+r.nt[1]+':'+r.nt[2]+'–'+r.nt[3],link(...r.nt)));if(!paired)box.append(make('p','Ce lien documenté ne qualifie pas automatiquement le rapprochement déjà proposé dans votre journée.','study-caption'));comparisons.append(box)}
comparisons.append(make('p','Les autres rapprochements du parcours sont des comparaisons proposées pour l’étude ; leur présence dans le plan ne prouve pas une citation ou un écho intentionnel. Comparez destinataires, vocabulaire, contexte et différences.'));const guide=make('a','Distinguer citation, écho probable et comparaison');guide.href='./rapprochements.html';comparisons.append(guide);resources.append(comparisons);
const hard=make('details');hard.append(make('summary','Un passage me paraît difficile'));hard.append(make('p','Identifiez qui parle, le genre et la situation. Un acte raconté n’est pas nécessairement approuvé ; une image poétique n’est pas une instruction à appliquer littéralement.'));const a=make('a','Violence, jugement, souffrance, lois et images : aides de lecture');a.href='./passages-difficiles.html';hard.append(a);resources.append(hard);
day.querySelector('#dailyNotesPanel')?.before(resources);if(!resources.isConnected)day.append(resources);if(focusedControl?.isConnected&&focusedControl.matches('[data-reading-mark]'))focusedControl.focus({preventScroll:true})}
if(content){new MutationObserver(add).observe(content,{childList:true});add()}
const library=document.getElementById('bookLibrary');if(library){const select=document.getElementById('bookChoice'),search=document.getElementById('bookSearch');Object.entries(db.books).forEach(([code,b])=>select.add(new Option(b.name,code)));const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();function show(){library.replaceChildren();let n=0;for(const [c,b]of Object.entries(db.books))if((!select.value||select.value===c)&&norm(b.name+' '+b.genre+' '+b.intro+' '+b.stage).includes(norm(search.value))){library.append(intro(c));n++}document.getElementById('bookCount').textContent=n+' livre(s) trouvé(s)'}select.onchange=show;search.oninput=show;const code=location.hash.slice(1);if(db.books[code])select.value=code;show()}
const comfortKey='bible-reading-comfort-v2',defaults={width:'760',leading:'1.7',spacing:'1'};let prefs={...defaults};try{const v=JSON.parse(localStorage.getItem(comfortKey)||'null');if(v&&['640','760','960'].includes(v.width)&&['1.5','1.7','1.9'].includes(v.leading)&&['.7','1','1.4'].includes(v.spacing))prefs=v}catch(_){}
function apply(){const root=document.documentElement;root.style.setProperty('--study-width',prefs.width+'px');root.style.setProperty('--study-leading',prefs.leading);root.style.setProperty('--study-spacing',prefs.spacing+'em')}apply();
if(content||library){const tools=document.getElementById('dailyTools')||document.querySelector('main');const open=make('button','Aperçu du confort de lecture');open.id='readingComfortPreview';open.type='button';tools.append(open);const dialog=make('dialog');dialog.id='readingComfortDialog';dialog.setAttribute('aria-labelledby','readingComfortTitle');dialog.innerHTML='<h2 id="readingComfortTitle">Confort de lecture</h2><p>Ces réglages concernent les explications et la présentation du parcours. Les textes ouverts sur un autre site utilisent ses propres réglages.</p><label for="readingWidth">Largeur</label><select id="readingWidth"><option value="640">Étroite</option><option value="760">Moyenne</option><option value="960">Large</option></select><label for="readingLeading">Interligne</label><select id="readingLeading"><option value="1.5">Normal</option><option value="1.7">Aéré</option><option value="1.9">Très aéré</option></select><label for="readingSpacing">Espacement des paragraphes</label><select id="readingSpacing"><option value=".7">Compact</option><option value="1">Normal</option><option value="1.4">Aéré</option></select><div id="readingSample" class="reading-sample"><p>Une lecture attentive prend le temps de suivre une pensée, un récit ou une image.</p><p>On peut revenir au paragraphe précédent, noter une question et poursuivre à son rythme.</p></div><p id="readingPreviewDescription" role="status"></p><button type="button" id="applyReadingComfort">Appliquer</button><button type="button" id="cancelReadingComfort">Annuler</button>';document.body.append(dialog);const controls=['readingWidth','readingLeading','readingSpacing'].map(id=>dialog.querySelector('#'+id)),sample=dialog.querySelector('#readingSample');function preview(){sample.style.maxWidth=controls[0].value+'px';sample.style.lineHeight=controls[1].value;sample.style.setProperty('--preview-spacing',controls[2].value+'em');dialog.querySelector('#readingPreviewDescription').textContent='Largeur maximale : '+controls[0].value+' pixels ; adaptée automatiquement à votre écran.'}open.onclick=()=>{controls.forEach((c,i)=>c.value=prefs[['width','leading','spacing'][i]]);preview();dialog.showModal()};controls.forEach(c=>c.onchange=preview);dialog.querySelector('#applyReadingComfort').onclick=()=>{prefs={width:controls[0].value,leading:controls[1].value,spacing:controls[2].value};apply();try{localStorage.setItem(comfortKey,JSON.stringify(prefs))}catch(_){}dialog.close();open.focus()};dialog.querySelector('#cancelReadingComfort').onclick=()=>{dialog.close();open.focus()}}
window.bibleStudy={bookOf,chapterOf,has,link};
})();
