const RELEASE='2026.10.04.33',CORE_CACHE='bible-core-v22',PLAN_CACHE='bible-selected-plans-v22';
const url=file=>new URL('./'+file,self.location.href).href,MANIFEST=url('release-manifest.json');
const CORE=['methode-israel-nations.html','notebook.js','plan-guide.js','version-notes.js','choisir-parcours.html','comparer-versions.html','book-guides.js','study.js','study.css','personal-home.js','livres.html','methode-continuite.html','passages-difficiles.html','rapprochements.html','relecture.html','review-kit.js','index.html','theme.css','theme.js','updates.js','app-common.js','daily-companion.js','application-help.js','nouveautes.html','validators.js','accessibility.js','editorial.js','mobile-audio.js','transfer.js','reminders.js','secure-backup.js','daily-view.js','offline-tools.js','recuperer-suivi.html','tests-telephone.html','phone-tests.js','qualite-des-plans.html','accessibilite.html','versions-bible.html','methode.html','methode-salut.html','methode-semaines.html','methode-nouveaux-plans.html','methode-famille.html','manifest.webmanifest','icon.svg','icon-180.png','icon-192.png','icon-512.png'].map(url);
const PLANS=['classique','genres','salut','semaines','chronologique','parallele','rattrapage','famille','continuite','israel-nations'].flatMap(p=>['','-lsg','-pdv'].map(v=>url('plan-'+p+v+'.html'))),SEARCH=url('recherche.html');
async function manifest(fresh=false){if(!fresh){const r=await(await caches.open(CORE_CACHE)).match(MANIFEST);if(r)return r.json()}const r=await fetch(MANIFEST,{cache:'no-store'});if(!r.ok)throw Error('manifest');const m=await r.json();if(m.version!==RELEASE||!m.files)throw Error('release');return m}
async function checkedFetch(u,m){const name=u.split('/').pop(),expected=m.files[name];if(!/^[a-f0-9]{64}$/.test(expected||''))throw Error('unlisted');const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('download');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await r.clone().arrayBuffer()))].map(v=>v.toString(16).padStart(2,'0')).join('');if(hash!==expected)throw Error('incomplete-release');return r}
async function downloadAll(files,m){const results=[];for(let i=0;i<files.length;i+=4)results.push(...await Promise.all(files.slice(i,i+4).map(async u=>[u,await checkedFetch(u,m)])));return results}
async function putAll(cache,entries){for(const [u,r]of entries)await cache.put(u,r)}
self.addEventListener('install',e=>e.waitUntil((async()=>{
try{const m=await manifest(true),selected=new Set();for(const name of await caches.keys())if(name.startsWith('bible-selected-plans-')&&name!==PLAN_CACHE)for(const r of await(await caches.open(name)).keys())if(PLANS.includes(r.url))selected.add(r.url);
// No active cache is changed until every requested file has passed verification.
const entries=await downloadAll([...CORE,...selected],m),core=await caches.open(CORE_CACHE),plans=await caches.open(PLAN_CACHE);await putAll(core,entries.filter(([u])=>CORE.includes(u)));await putAll(plans,entries.filter(([u])=>PLANS.includes(u)));await core.put(MANIFEST,new Response(JSON.stringify(m),{headers:{'Content-Type':'application/json'}}));await self.skipWaiting()
}catch(err){await caches.delete(CORE_CACHE);await caches.delete(PLAN_CACHE);throw err}
})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(/^(bible-core-|bible-selected-plans-|bible-multi-plans-|bible-plan-offline-)/.test(k)&&![CORE_CACHE,PLAN_CACHE].includes(k))await caches.delete(k);await self.clients.claim()})()));
function unavailable(){return new Response('<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page indisponible</title><body style="font:18px/1.6 system-ui;padding:24px"><h1>Cette page n’est pas disponible</h1><p>Reconnectez-vous puis vérifiez les mises à jour avant de télécharger ce parcours. Votre suivi reste conservé dans ce navigateur.</p><a href="./index.html?choisir=1">Choisir un parcours</a></body></html>',{status:503,headers:{'Content-Type':'text/html; charset=utf-8'}})}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;let key=u.origin+u.pathname;if(key===new URL('./',self.location.href).href)key=url('index.html');if(!CORE.includes(key)&&!PLANS.includes(key)&&key!==SEARCH)return;e.respondWith((async()=>{const c=await caches.open(PLANS.includes(key)?PLAN_CACHE:CORE_CACHE),saved=await c.match(key);if(saved)return saved;try{const r=await checkedFetch(key,await manifest());await c.put(key,r.clone());return r}catch(_){return unavailable()}})())});
self.addEventListener('message',e=>{const d=e.data||{};e.waitUntil((async()=>{const c=await caches.open(PLAN_CACHE);switch(d.type){
case 'LIST_OFFLINE':return {ok:true,files:(await c.keys()).map(r=>r.url.split('/').pop()).sort()};
case 'PREPARE_PLANS':{if(!Array.isArray(d.files)||d.files.length>30)throw Error('files');const files=d.files.map(url);if(files.some(f=>!PLANS.includes(f)))throw Error('files');const entries=await downloadAll(files,await manifest());await putAll(c,entries);return {ok:true}};
case 'REMOVE_PLAN':if(!PLANS.includes(url(d.file)))throw Error('file');await c.delete(url(d.file));return {ok:true};
case 'REFRESH_APP':{const m=await manifest(true),selected=(await c.keys()).map(r=>r.url),entries=await downloadAll([...CORE,...selected],m);await putAll(await caches.open(CORE_CACHE),entries.filter(([u])=>CORE.includes(u)));await putAll(c,entries.filter(([u])=>PLANS.includes(u)));return {ok:true,version:RELEASE}};
default:throw Error('message')}})().then(r=>e.ports[0]?.postMessage(r)).catch(()=>e.ports[0]?.postMessage({ok:false})))}); 
