const CORE_CACHE='bible-core-v17',PLAN_CACHE='bible-selected-plans-v17';
const url=file=>new URL('./'+file,self.location.href).href;
const CORE=['index.html','theme.css','theme.js','updates.js','mobile-audio.js','transfer.js','reminders.js','secure-backup.js','daily-view.js','offline-tools.js','recuperer-suivi.html','tests-telephone.html','phone-tests.js','versions-bible.html','methode.html','methode-salut.html','methode-semaines.html','methode-nouveaux-plans.html','methode-famille.html','manifest.webmanifest','icon.svg','icon-180.png','icon-192.png','icon-512.png'].map(url);
const PLANS=['classique','genres','salut','semaines','chronologique','parallele','rattrapage','famille'].flatMap(p=>['','-lsg','-pdv'].map(v=>url('plan-'+p+v+'.html')));
const SEARCH=url('recherche.html');
async function refreshFiles(cache,files){await cache.addAll(files.map(u=>new Request(u,{cache:'reload'})))}
self.addEventListener('install',e=>e.waitUntil((async()=>{await refreshFiles(await caches.open(CORE_CACHE),CORE);const saved=new Set();for(const name of await caches.keys()){if(name.startsWith('bible-selected-plans-')&&name!==PLAN_CACHE){const c=await caches.open(name);for(const r of await c.keys())if(PLANS.includes(r.url))saved.add(r.url)}}if(saved.size)await refreshFiles(await caches.open(PLAN_CACHE),[...saved]);await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(/^(bible-core-|bible-selected-plans-|bible-multi-plans-|bible-plan-offline-)/.test(k)&&![CORE_CACHE,PLAN_CACHE].includes(k))await caches.delete(k);await self.clients.claim()})()));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;let key=u.origin+u.pathname;if(key===new URL('./',self.location.href).href)key=url('index.html');if(!CORE.includes(key)&&!PLANS.includes(key)&&key!==SEARCH)return;e.respondWith((async()=>{const c=await caches.open(PLANS.includes(key)?PLAN_CACHE:CORE_CACHE);try{const response=await fetch(e.request);if(response.ok)await c.put(key,response.clone());return response}catch(_){const saved=await c.match(key);if(saved)return saved;return new Response('<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Parcours non téléchargé</title><body style="font:18px/1.6 system-ui;padding:24px"><h1>Cette page n’est pas disponible hors connexion</h1><p>Reconnectez-vous puis téléchargez ce parcours dans « Mes parcours hors connexion ». Votre suivi reste conservé dans ce navigateur.</p><a href="./index.html?choisir=1">Choisir un parcours</a></body></html>',{status:503,headers:{'Content-Type':'text/html; charset=utf-8'}})}})())});
self.addEventListener('message',e=>{const d=e.data||{};e.waitUntil((async()=>{const c=await caches.open(PLAN_CACHE);switch(d.type){case 'LIST_OFFLINE':return {ok:true,files:(await c.keys()).map(r=>r.url.split('/').pop()).sort()};case 'PREPARE_PLANS':{if(!Array.isArray(d.files)||d.files.length>24)throw Error('files');const files=d.files.map(url);if(files.some(f=>!PLANS.includes(f)))throw Error('files');await refreshFiles(c,files);return {ok:true}}case 'REMOVE_PLAN':if(!PLANS.includes(url(d.file)))throw Error('file');await c.delete(url(d.file));return {ok:true};case 'REFRESH_APP':await refreshFiles(await caches.open(CORE_CACHE),CORE);await refreshFiles(c,(await c.keys()).map(r=>r.url));return {ok:true};default:throw Error('message')}})().then(result=>e.ports[0]?.postMessage(result)).catch(()=>e.ports[0]?.postMessage({ok:false})))});
