'use strict';
// Shared validation; plan-specific identity checks remain in each page.
function validChapterFavorites(value){return Array.isArray(value)&&value.length<=chapterIndex.size&&value.every(id=>typeof id==='string'&&chapterIndex.has(id))}
function validReviews(value){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length<=chapterIndex.size&&Object.entries(value).every(([id,r])=>chapterIndex.has(id)&&r&&typeof r==='object'&&typeof r.note==='string'&&r.note.length<=1000&&typeof r.reviewed==='boolean')}
function validHistory(value){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length<=365&&Object.entries(value).every(([day,versions])=>/^[1-9][0-9]*$/.test(day)&&Number(day)<=365&&Array.isArray(versions)&&versions.length<=3&&versions.every(v=>v&&typeof v.text==='string'&&v.text.length<=10000&&typeof v.savedAt==='string'&&Number.isFinite(Date.parse(v.savedAt))))}
function validReadingMarks(value){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length<=chapterIndex.size&&Object.entries(value).every(([id,r])=>chapterIndex.has(id)&&r&&typeof r.position==='string'&&r.position.length<=200&&Number.isInteger(r.day)&&r.day>=1&&r.day<=365&&days[r.day-1].cards.some(c=>c.entries.some(e=>e.page.split('/').pop()===id)))}
function validTopics(value){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length<=365&&Object.entries(value).every(([day,tags])=>/^[1-9][0-9]*$/.test(day)&&Number(day)<=365&&Array.isArray(tags)&&tags.length<=8&&tags.every(t=>typeof t==='string'&&t.trim().length>0&&t.length<=40))}
function validNotes(value){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length<=365&&Object.entries(value).every(([k,v])=>/^[1-9]\d*$/.test(k)&&Number(k)<=365&&typeof v==='string'&&v.length<=10000)}
function validArchive(a){return a&&typeof a==='object'&&typeof a.id==='string'&&a.id.length>0&&a.id.length<=100&&typeof a.label==='string'&&a.label.length<=100&&typeof a.archivedAt==='string'&&Number.isFinite(Date.parse(a.archivedAt))&&validNotes(a.notes)&&Array.isArray(a.completedDays)&&a.completedDays.length<=365&&a.completedDays.every(valid)&&Array.isArray(a.favorites)&&a.favorites.length<=365&&a.favorites.every(valid)&&valid(a.lastDay)&&(a.startDate===''||validStartDate(a.startDate))&&(a.chapterFavorites===undefined||validChapterFavorites(a.chapterFavorites))&&(a.listenedChapters===undefined||validChapterFavorites(a.listenedChapters))&&(a.monthlyReflections===undefined||validMonthly(a.monthlyReflections))&&(a.passageReviews===undefined||validReviews(a.passageReviews))&&(a.noteHistory===undefined||validHistory(a.noteHistory))&&(a.readingMarks===undefined||validReadingMarks(a.readingMarks))&&(a.noteTopics===undefined||validTopics(a.noteTopics))}
function validMonthly(value){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length<=12&&Object.entries(value).every(([month,text])=>/^(?:[1-9]|1[0-2])$/.test(month)&&typeof text==='string'&&text.length<=10000)}
function validStartDate(v){return Number.isFinite(dateNumber(v))}
