(()=>{
'use strict';
const records=[
{id:'genese-vide',title:'Genèse 1:2 — décrire la terre',text:'Les trois formulations décrivent l’état initial de la terre avec des mots différents. Comparez aussi la suite du verset et la progression du récit ; un choix de vocabulaire ne suffit pas à établir une différence doctrinale.',refs:{s21:['GEN',1,2,2],lsg:['GEN',1,2,2],pdv:['GEN',1,2,2]},excerpts:{s21:'« chaos et vide »',lsg:'« informe et vide »',pdv:'« comme un grand vide »'}},
{id:'matthieu-pauvre',title:'Matthieu 5:3 — la première béatitude',text:'Louis Segond conserve une expression brève ; Segond 21 explicite la pauvreté comme spirituelle ; Parole de Vie emploie une image du cœur. Relisez toute la béatitude et les paroles qui suivent pour discuter ce que chaque formulation met en relief.',refs:{s21:['MAT',5,3,3],lsg:['MAT',5,3,3],pdv:['MAT',5,3,3]},excerpts:{s21:'« leur pauvreté spirituelle »',lsg:'« pauvres en esprit »',pdv:'« un cœur de pauvre »'}},
{id:'joel-esprit',title:'Joël — retrouver l’annonce du don de l’Esprit',text:'Le même passage porte des numéros différents : Joël 3:1–5 en Segond 21 et Parole de Vie correspond à Joël 2:28–32 en Louis Segond. La différence de numéro ne signifie pas qu’un passage manque.',refs:{s21:['JOL',3,1,5],lsg:['JOL',2,28,32],pdv:['JOL',3,1,5]}},
{id:'malachie-fin',title:'Malachie — retrouver la fin du livre',text:'Malachie 3:19–24 en Segond 21 et Parole de Vie correspond à Malachie 4:1–6 en Louis Segond. Utilisez ces références pour comparer la fin du livre, sans changer les numéros du parcours déjà suivi.',refs:{s21:['MAL',3,19,24],lsg:['MAL',4,1,6],pdv:['MAL',3,19,24]}}
];
const names={s21:'Segond 21',lsg:'Louis Segond 1910',pdv:'Parole de Vie 2017'},bookNames={GEN:'Genèse',MAT:'Matthieu',JOL:'Joël',MAL:'Malachie'},ids={s21:152,lsg:93,pdv:133},suffix={s21:'S21',lsg:'LSG',pdv:'PDV2017'};
const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e};
function url(v,r){return 'https://www.bible.com/fr/bible/'+ids[v]+'/'+r[0]+'.'+r[1]+'.'+r[2]+(r[3]!==r[2]?'-'+r[3]:'')+'.'+suffix[v]}
function article(r){const box=el('article');box.className='version-comparison';box.append(el('h3',r.title),el('p',r.text));const list=el('ul');for(const v of ['s21','lsg','pdv']){const p=r.refs[v],li=el('li'),a=el('a',names[v]+' — '+bookNames[p[0]]+' '+p[1]+':'+p[2]+(p[3]!==p[2]?'–'+p[3]:''));a.href=url(v,p);a.target='_blank';a.rel='noopener noreferrer';li.append(a);if(r.excerpts?.[v])li.append(document.createTextNode(' : '+r.excerpts[v]));list.append(li)}box.append(list);if(r.excerpts)box.append(el('p','Courts fragments cités pour comparer le vocabulaire ; ouvrez les liens pour lire les versets complets.'));return box}
const library=document.getElementById('versionComparisonLibrary');if(library)records.forEach(r=>library.append(article(r)));
const content=document.getElementById('content'),version=location.pathname.includes('-lsg.html')?'lsg':location.pathname.includes('-pdv.html')?'pdv':'s21';
function intersects(e,ref){const match=e.page?.match(/\/([A-Z0-9]+)\.(\d+)/),book=e.book||match?.[1],chapter=Number(e.chapter||match?.[2]);return book===ref[0]&&chapter===ref[1]&&(e.firstVerse||1)<=ref[3]&&(e.lastVerse||Infinity)>=ref[2]}
function add(){const day=content?.querySelector('.day');if(!day||day.querySelector('.day-version-notes'))return;const entries=days[current-1].cards.flatMap(c=>c.entries),relevant=records.filter(r=>entries.some(e=>intersects(e,r.refs[version])));const box=el('details');box.className='day-version-notes';box.append(el('summary','Repères entre les versions'+(relevant.length?' — '+relevant.length+' comparaison(s)':'')));if(relevant.length)relevant.forEach(r=>box.append(article(r)));else box.append(el('p','Aucune différence ponctuelle documentée dans ce premier catalogue pour les passages de cette journée.'));box.append(el('p','Ces liens comparent les textes sans changer votre version, vos coches ni vos notes. Le texte Louis Segond est consulté sur YouVersion ; l’audio de votre parcours reste celui de Trésor Sonore.'));const more=el('a','Voir les quatre repères documentés');more.href='./comparer-versions.html';box.append(more);(day.querySelector('.study-resources')||day).append(box)}
if(content){new MutationObserver(add).observe(content,{childList:true});add()}
window.bibleVersionComparisons={records,url,intersects};
})();
